'use client'

import {useEffect,useState} from 'react'
import {supabase} from '../../../lib/supabase'

export default function AdminLegalPage(){
 const [checked,setChecked]=useState(false),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true),[items,setItems]=useState([]),[shops,setShops]=useState({}),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function load(){setLoading(true);setError('');const {data,error:ae}=await supabase.auth.getUser();const ok=!ae&&data?.user?.app_metadata?.role==='admin';setAdmin(ok);setChecked(true);if(!ok){setLoading(false);return}
  const [{data:l,error:le},{data:b,error:be}]=await Promise.all([supabase.from('boutique_legal_onboarding').select('id,boutique_id,user_id,legal_name,document_type,document_number,document_url,terms_version,terms_accepted,terms_accepted_at,verification_status,reviewed_at,review_note,created_at').order('created_at',{ascending:false}),supabase.from('boutiques').select('id,name,plan,is_live,legal_verification_status')])
  if(le||be)setError(le?.message||be?.message);else{setItems(l||[]);setShops(Object.fromEntries((b||[]).map(x=>[x.id,x])))}setLoading(false)
 }
 useEffect(()=>{load()},[])
 async function openDocument(item){setBusy(`doc-${item.id}`);setError('');const {data,error:e}=await supabase.storage.from('boutique-legal-documents').createSignedUrl(item.document_url,120);setBusy('');if(e||!data?.signedUrl)return setError(e?.message||'Document indisponible');window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 async function decide(item,decision){const label=decision==='approved'?'approuver':'rejeter';if(!window.confirm(`Confirmer : ${label} la vérification de ${item.legal_name} ?`))return;setBusy(`review-${item.id}`);setError('');setMessage('');const note=decision==='rejected'?(window.prompt('Motif du refus (recommandé) :')||'').trim():'';const {error:e}=await supabase.rpc('admin_review_boutique_legal',{p_onboarding_id:item.id,p_decision:decision,p_note:note||null});if(e)setError(e.message);else{setMessage(decision==='approved'?'✅ وثائق وعقد البوتيك معتمدان. ارجع للوحة الإدارة واضغط «منح المجانية» إذا أردت إعفاءها من الأداء.':'Vérification refusée. La boutique reste inactive.');await load()}setBusy('')}
 if(!checked||loading)return <main style={page}><div style={card}>Chargement…</div></main>
 if(!admin)return <main style={page}><div style={card}><h1>Administration protégée</h1><p>Accès réservé à l’administrateur WakhReek.</p><a href="/admin">Retour</a></div></main>
 const pending=items.filter(x=>x.verification_status==='pending'||x.verification_status==='needs_review'),history=items.filter(x=>!pending.includes(x))
 return <main style={page}><div style={{maxWidth:1150,margin:'0 auto'}}><header style={header}><div><a href="/admin">← Tableau de bord</a><h1>مراجعة الوثائق والعقد</h1><p>راجع الوثيقة والعقد أولاً. بعد الاعتماد يمكنك منح البوتيك صلاحية مجانية من لوحة الإدارة بدون أداء.</p></div><button style={btn('#0066ff')} onClick={load}>Actualiser</button></header>{message&&<div style={{...card,borderLeft:'5px solid #12b76a'}}>{message}</div>}{error&&<div style={{...card,color:'#b42318',borderLeft:'5px solid #d92d20'}}>{error}</div>}<section style={card}><h2>À vérifier ({pending.length})</h2>{pending.length===0?<p>Aucune demande juridique en attente.</p>:pending.map(x=><Review key={x.id} item={x} shop={shops[x.boutique_id]} busy={busy} openDocument={openDocument} decide={decide}/>)}</section><section style={{...card,marginTop:20}}><h2>Historique ({history.length})</h2>{history.length===0?<p>Aucune décision enregistrée.</p>:history.map(x=><Review key={x.id} item={x} shop={shops[x.boutique_id]} busy={busy} openDocument={openDocument} decide={decide} history/>)}</section></div></main>
}
function Review({item,shop,busy,openDocument,decide,history}){const status=item.verification_status==='approved'?'✅ Approuvé':item.verification_status==='rejected'?'❌ Refusé':'⏳ En attente';return <article style={itemStyle}><div style={grid}><Info l="Boutique" v={shop?.name||'—'}/><Info l="Responsable légal" v={item.legal_name}/><Info l="Document" v={`${docLabel(item.document_type)} • ${mask(item.document_number)}`}/><Info l="Contrat" v={`${item.terms_version} • ${item.terms_accepted?'accepté':'non accepté'}`}/><Info l="Accepté le" v={item.terms_accepted_at?new Date(item.terms_accepted_at).toLocaleString('fr-FR'):'—'}/><Info l="État" v={status}/></div>{item.review_note&&<p><b>Note :</b> {item.review_note}</p>}<div style={{marginTop:14,display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={busy===`doc-${item.id}`} onClick={()=>openDocument(item)} style={btn('#344054')}>Voir le document privé</button>{!history&&<><button disabled={!!busy} onClick={()=>decide(item,'approved')} style={btn('#12b76a')}>✅ اعتماد الوثائق والعقد</button><button disabled={!!busy} onClick={()=>decide(item,'rejected')} style={btn('#d92d20')}>Refuser</button></>}</div></article>}
function Info({l,v}){return <div><small style={{color:'#667085'}}>{l}</small><strong style={{display:'block',marginTop:4}}>{v}</strong></div>}
function docLabel(x){return x==='id_card'?'Carte d’identité':x==='passport'?'Passeport':x==='business_registration'?'Registre / entreprise':'Document officiel'}
function mask(x){if(!x)return'—';const s=String(x);return s.length<=4?'••••':`${'•'.repeat(Math.min(8,s.length-4))}${s.slice(-4)}`}
const page={minHeight:'100vh',background:'#f4f7fb',padding:24,fontFamily:'Arial,sans-serif',color:'#172033'},card={background:'#fff',borderRadius:16,padding:20,boxShadow:'0 4px 18px #1028400f'},header={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap',marginBottom:20},grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:14},itemStyle={border:'1px solid #eaecf0',borderRadius:12,padding:16,marginTop:12},btn=background=>({border:0,borderRadius:9,padding:'10px 13px',background,color:'#fff',fontWeight:700,cursor:'pointer'})