'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {supabase} from '../../../lib/supabase'

export default function Finance(){const[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
async function load(){setLoading(true);setError('');const{data,error}=await supabase.rpc('admin_financial_dashboard');if(error)setError(error.message);else setData(data);setLoading(false)}
useEffect(()=>{load()},[])
const n=v=>`${Number(v||0).toLocaleString()} CFA`
return <main style={page}><div style={{maxWidth:1100,margin:'0 auto'}}><header style={head}><div><h1>💰 Finance WakhReek</h1><p>Seuls les paiements confirmés sont comptés comme revenus.</p></div><div><Link href="/admin" style={link}>← Admin</Link><button onClick={load} style={btn}>Actualiser</button></div></header>{error&&<div style={err}>{error}</div>}{loading?<div style={card}>Chargement…</div>:data&&<><section style={grid}><Stat label="Revenu aujourd’hui — Boutiques" value={n(data.boutique_revenue_today_cfa)}/><Stat label="Revenu ce mois — Boutiques" value={n(data.boutique_revenue_month_cfa)}/><Stat label="Revenu total — Boutiques" value={n(data.boutique_revenue_total_cfa)}/><Stat label="Revenu total — Services" value={n(data.service_revenue_total_cfa)}/><Stat label="Paiements boutiques en attente" value={data.boutique_pending_count||0}/><Stat label="Paiements boutiques confirmés" value={data.boutique_approved_count||0}/><Stat label="Services en attente" value={data.service_pending_count||0}/><Stat label="Services payés" value={data.service_paid_count||0}/></section><section style={card}><h2>Wave / Orange Money — paiements boutiques confirmés</h2>{(data.by_method||[]).length===0?<p>Aucun paiement confirmé.</p>:(data.by_method||[]).map(x=><div key={x.method} style={row}><strong>{x.method==='wave'?'Wave':x.method==='orange_money'?'Orange Money':x.method}</strong><span>{x.transactions} opération(s) · {n(x.amount)}</span></div>)}</section><p style={{fontSize:13,color:'#667085'}}>Les revenus publicitaires ne sont pas encore additionnés : aucune donnée de paiement publicitaire confirmée n’est enregistrée dans market_tv_ads. Ils seront comptés seulement après création d’un vrai flux de paiement publicitaire.</p></>}</div></main>}
function Stat({label,value}){return <div style={card}><small>{label}</small><div style={{fontSize:26,fontWeight:800,marginTop:6}}>{value}</div></div>}
const page={minHeight:'100vh',padding:24,background:'#f4f7fb',fontFamily:'Arial,sans-serif',color:'#172033'},head={display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap',marginBottom:20},grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:14,marginBottom:20},card={background:'#fff',borderRadius:16,padding:20,boxShadow:'0 4px 18px #1028400f'},row={display:'flex',justifyContent:'space-between',gap:12,padding:'12px 0',borderBottom:'1px solid #eaecf0'},btn={border:0,borderRadius:10,padding:'10px 14px',background:'#0066ff',color:'#fff',fontWeight:700,cursor:'pointer'},link={textDecoration:'none',color:'#0066ff',marginRight:10},err={background:'#fff0f0',color:'#a00',padding:12,borderRadius:10,marginBottom:14}
