'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'

export default function AdminPage() {
  const [authChecked,setAuthChecked]=useState(false),[isAdmin,setIsAdmin]=useState(false),[loading,setLoading]=useState(true)
  const [actionBusy,setActionBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const [boutiques,setBoutiques]=useState([]),[subscriptions,setSubscriptions]=useState([]),[tvAds,setTvAds]=useState([])

  async function verifyAdmin(){const{data,error:authError}=await supabase.auth.getUser();const admin=!authError&&data?.user?.app_metadata?.role==='admin';setIsAdmin(admin);setAuthChecked(true);return admin}
  async function loadAdminData(){setLoading(true);setError('');const admin=await verifyAdmin();if(!admin){setLoading(false);return}const[b,s,a]=await Promise.all([supabase.from('boutiques').select('id,name,plan,is_live,created_at').order('created_at',{ascending:false}),supabase.from('subscriptions').select('id,boutique_id,plan,country_code,amount_cfa,status,created_at,payment_method,payment_type,billing_currency,billing_amount,payment_reference,payment_selected_at,payment_submitted_at').order('created_at',{ascending:false}),supabase.from('market_tv_ads').select('id,boutique_id,title,description,media_url,media_type,duration_seconds,status,starts_at,ends_at,created_at').order('created_at',{ascending:false})]);if(b.error||s.error||a.error)setError(b.error?.message||s.error?.message||a.error?.message||'Erreur de chargement');else{setBoutiques(b.data||[]);setSubscriptions(s.data||[]);setTvAds(a.data||[])}setLoading(false)}
  useEffect(()=>{loadAdminData()},[])
  const subscriptionsByBoutique=useMemo(()=>{const m=new Map();for(const x of subscriptions)if(!m.has(x.boutique_id))m.set(x.boutique_id,x);return m},[subscriptions])
  const boutiquesById=useMemo(()=>new Map(boutiques.map(b=>[b.id,b])),[boutiques])
  const waiting=subscriptions.filter(s=>s.status==='pending'&&!paymentSubmitted(s)),review=subscriptions.filter(s=>s.status==='pending'&&paymentSubmitted(s)),approved=subscriptions.filter(s=>s.status==='approved'),rejected=subscriptions.filter(s=>s.status==='rejected')
  const liveCount=boutiques.filter(x=>x.is_live).length,pendingTv=tvAds.filter(x=>x.status==='pending').length

  async function setBoutiqueLive(id,isLive,msg){setActionBusy(`boutique-${id}`);setError('');setNotice('');const{error:e}=await supabase.from('boutiques').update({is_live:isLive}).eq('id',id);if(e)setError(e.message);else{setNotice(msg);await loadAdminData()}setActionBusy('')}
  async function approveSubscription(s,boutiqueId){if(!paymentSubmitted(s)){setError('Ce paiement n’a pas encore été soumis par le vendeur.');return}setActionBusy(`subscription-${s.id}`);setError('');setNotice('');const{error:e}=await supabase.from('subscriptions').update({status:'approved'}).eq('id',s.id);if(e){setError(e.message);setActionBusy('');return}const{error:b}=await supabase.from('boutiques').update({is_live:true}).eq('id',boutiqueId);if(b)setError(b.message);else{setNotice('Paiement approuvé et boutique activée.');await loadAdminData()}setActionBusy('')}
  async function rejectSubscription(s,boutiqueId){setActionBusy(`subscription-${s.id}`);setError('');setNotice('');const{error:e}=await supabase.from('subscriptions').update({status:'rejected'}).eq('id',s.id);if(e){setError(e.message);setActionBusy('');return}const{error:b}=await supabase.from('boutiques').update({is_live:false}).eq('id',boutiqueId);if(b)setError(b.message);else{setNotice('Paiement refusé et boutique désactivée.');await loadAdminData()}setActionBusy('')}
  async function setTvStatus(ad,status){setActionBusy(`tv-${ad.id}`);setError('');setNotice('');const patch={status};if(status==='active'&&!ad.starts_at)patch.starts_at=new Date().toISOString();if(status==='ended')patch.ends_at=new Date().toISOString();const{error:e}=await supabase.from('market_tv_ads').update(patch).eq('id',ad.id);if(e)setError(e.message);else{setNotice(status==='active'?'Publicité TV approuvée et activée.':status==='rejected'?'Publicité TV refusée.':status==='paused'?'Publicité TV mise en pause.':'Publicité TV terminée.');await loadAdminData()}setActionBusy('')}

  if(!authChecked||loading)return <main style={pageStyle}><div style={cardStyle}>Vérification Admin...</div></main>
  if(!isAdmin)return <main style={pageStyle}><div style={{...cardStyle,maxWidth:560,margin:'80px auto',textAlign:'center'}}><h1 style={{marginTop:0}}>Accès Admin protégé</h1><p style={{color:'#667085'}}>Cette page est réservée au compte administrateur WakhReek.</p><a href="/" style={{color:'#0066ff',fontWeight:700}}>Retour à WakhReek</a></div></main>

  return <main style={pageStyle}><div style={{maxWidth:1280,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap',marginBottom:24}}><div><h1 style={{margin:0,fontSize:30}}>WakhReek Admin</h1><p style={{margin:'6px 0 0',color:'#667085'}}>Gestion protégée des boutiques, paiements et WakhReek TV</p></div><button onClick={loadAdminData} style={buttonStyle('#0066ff')}>Actualiser</button></div>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:14,marginBottom:22}}><Stat label="Boutiques" value={boutiques.length}/><Stat label="Boutiques actives" value={liveCount}/><Stat label="Pas encore soumis" value={waiting.length}/><Stat label="À vérifier" value={review.length}/><Stat label="Paiements approuvés" value={approved.length}/><Stat label="Paiements refusés" value={rejected.length}/><Stat label="Publicités TV en attente" value={pendingTv}/></section>
    {notice&&<div style={{...cardStyle,border:'1px solid #12b76a',color:'#027a48',marginBottom:18}}>{notice}</div>}{error&&<div style={{...cardStyle,border:'1px solid #f04438',color:'#b42318',marginBottom:18}}>Erreur: {error}</div>}

    <PaymentSection title="💳 Paiements à vérifier" description="Références envoyées par les vendeurs et prêtes pour contrôle Admin." items={review} boutiquesById={boutiquesById} actionBusy={actionBusy} onApprove={approveSubscription} onReject={rejectSubscription} mode="review"/>
    <PaymentSection title="⏳ Paiements pas encore soumis" description="Le vendeur n’a pas encore envoyé de référence de transaction. Aucune approbation de paiement n’est possible." items={waiting} boutiquesById={boutiquesById} actionBusy={actionBusy} onReject={rejectSubscription} mode="waiting"/>
    <PaymentSection title="✅ Paiements approuvés" description="Historique des abonnements dont le paiement a été approuvé." items={approved} boutiquesById={boutiquesById} actionBusy={actionBusy} mode="history"/>
    <PaymentSection title="❌ Paiements refusés" description="Historique des abonnements refusés." items={rejected} boutiquesById={boutiquesById} actionBusy={actionBusy} mode="history"/>

    <section style={{...cardStyle,marginBottom:20}}><h2 style={{marginTop:0}}>📺 Division Publicité — WakhReek TV</h2><p style={{color:'#667085'}}>Les vidéos commerçants restent en attente jusqu’à validation Admin. La durée est informative et n’impose aucune plage obligatoire.</p>{tvAds.length===0?<p style={{color:'#667085'}}>Aucune publicité TV pour le moment.</p>:<div style={{display:'grid',gap:14}}>{tvAds.map(ad=>{const busy=actionBusy===`tv-${ad.id}`,shop=boutiquesById.get(ad.boutique_id),hasDuration=ad.duration_seconds!==null&&ad.duration_seconds!==undefined&&Number.isFinite(Number(ad.duration_seconds));return <article key={ad.id} style={{border:'1px solid #eaecf0',borderRadius:14,padding:14,display:'grid',gridTemplateColumns:'minmax(240px,360px) 1fr',gap:16}}><video src={ad.media_url} controls preload="metadata" style={{width:'100%',maxHeight:230,background:'#000',borderRadius:10}}/><div><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><strong style={{fontSize:18}}>{ad.title}</strong><div style={{color:'#667085',marginTop:4}}>{shop?.name||'Boutique'}{hasDuration?` • ${Number(ad.duration_seconds).toFixed(1)} s`:''}</div></div><b>{tvLabel(ad.status)}</b></div>{ad.description&&<p>{ad.description}</p>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{['pending','rejected','paused'].includes(ad.status)&&<button disabled={busy} onClick={()=>setTvStatus(ad,'active')} style={buttonStyle('#12b76a')}>{busy?'...':'Approuver / Activer'}</button>}{ad.status!=='rejected'&&ad.status!=='ended'&&<button disabled={busy} onClick={()=>setTvStatus(ad,'rejected')} style={buttonStyle('#d92d20')}>{busy?'...':'Refuser'}</button>}{ad.status==='active'&&<button disabled={busy} onClick={()=>setTvStatus(ad,'paused')} style={buttonStyle('#f79009')}>Pause</button>}{(ad.status==='active'||ad.status==='paused')&&<button disabled={busy} onClick={()=>setTvStatus(ad,'ended')} style={buttonStyle('#667085')}>Terminer</button>}</div></div></article>})}</div>}</section>

    <section style={cardStyle}><h2 style={{marginTop:0}}>Boutiques</h2><p style={{color:'#667085'}}>L’activation gratuite Admin reste indépendante du circuit de paiement.</p>{boutiques.length===0?<p style={{color:'#667085'}}>Aucune boutique pour le moment.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1080}}><thead><tr>{['Boutique','Plan','Paiement','Montant','État','Créée le','Actions Admin'].map(t=><th key={t} style={thStyle}>{t}</th>)}</tr></thead><tbody>{boutiques.map(b=>{const s=subscriptionsByBoutique.get(b.id),bb=actionBusy===`boutique-${b.id}`,bs=s&&actionBusy===`subscription-${s.id}`,busy=bb||bs;return <tr key={b.id}><td style={tdStyle}><strong>{b.name}</strong></td><td style={tdStyle}>{b.plan||'-'}</td><td style={tdStyle}>{s?paymentState(s):'Aucun paiement'}</td><td style={tdStyle}>{paymentMoney(s)}</td><td style={tdStyle}>{b.is_live?'Active':'Inactive'}</td><td style={tdStyle}>{b.created_at?new Date(b.created_at).toLocaleDateString('fr-FR'):'-'}</td><td style={{...tdStyle,minWidth:290}}><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{!b.is_live&&<button disabled={busy} onClick={()=>setBoutiqueLive(b.id,true,'Boutique activée gratuitement par Admin.')} style={buttonStyle('#7f56d9')}>{bb?'...':'Activer gratuit'}</button>}{b.is_live&&<button disabled={busy} onClick={()=>setBoutiqueLive(b.id,false,'Boutique désactivée par Admin.')} style={buttonStyle('#667085')}>{bb?'...':'Désactiver'}</button>}{s?.status==='pending'&&paymentSubmitted(s)&&<><button disabled={busy} onClick={()=>approveSubscription(s,b.id)} style={buttonStyle('#12b76a')}>{bs?'...':'Approuver paiement'}</button><button disabled={busy} onClick={()=>rejectSubscription(s,b.id)} style={buttonStyle('#d92d20')}>{bs?'...':'Refuser paiement'}</button></>}</div></td></tr>})}</tbody></table></div>}</section>
  </div><style jsx>{`@media(max-width:720px){article{grid-template-columns:1fr!important}}`}</style></main>
}
function PaymentSection({title,description,items,boutiquesById,actionBusy,onApprove,onReject,mode}){return <section style={{...cardStyle,marginBottom:20}}><h2 style={{marginTop:0}}>{title}</h2><p style={{color:'#667085'}}>{description}</p>{items.length===0?<p style={{color:'#667085'}}>Aucun élément.</p>:<div style={{display:'grid',gap:12}}>{items.map(s=>{const b=boutiquesById.get(s.boutique_id),busy=actionBusy===`subscription-${s.id}`;return <article key={s.id} style={{border:'1px solid #eaecf0',borderRadius:12,padding:14}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10}}><Info label="Boutique" value={b?.name||'—'}/><Info label="Pays" value={s.country_code||'—'}/><Info label="Moyen" value={s.payment_method||'Non configuré'}/><Info label="Montant" value={paymentMoney(s)}/><Info label="Référence" value={s.payment_reference||'Pas encore soumise'}/><Info label="Soumis le" value={s.payment_submitted_at?new Date(s.payment_submitted_at).toLocaleString('fr-FR'):'—'}/></div>{mode!=='history'&&<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{mode==='review'&&<button disabled={busy} onClick={()=>onApprove(s,s.boutique_id)} style={buttonStyle('#12b76a')}>{busy?'...':'Approuver le paiement'}</button>}{onReject&&<button disabled={busy} onClick={()=>onReject(s,s.boutique_id)} style={buttonStyle('#d92d20')}>{busy?'...':'Refuser'}</button>}{mode==='waiting'&&<span style={{padding:'9px 0',color:'#b54708',fontWeight:700}}>{s.payment_method?'⏳ Référence vendeur attendue':'Moyen de paiement non configuré'}</span>}</div>}</article>})}</div>}</section>}
function paymentSubmitted(s){return !!(s?.payment_method&&s?.payment_reference&&s?.payment_submitted_at)}
function paymentState(s){if(s.status==='approved')return '✅ Approuvé';if(s.status==='rejected')return '❌ Refusé';if(paymentSubmitted(s))return '🔎 À vérifier';return '⏳ Pas encore soumis'}
function paymentMoney(s){if(!s)return '—';if(s.billing_amount!=null&&s.billing_currency)return `${Number(s.billing_amount).toLocaleString('fr-FR',{maximumFractionDigits:2})} ${s.billing_currency==='XOF'?'CFA':s.billing_currency}`;return s.amount_cfa!=null?`${Number(s.amount_cfa).toLocaleString('fr-FR')} CFA`:'—'}
function Info({label,value}){return <div style={{background:'#f8fafc',borderRadius:9,padding:10}}><small style={{display:'block',color:'#667085',marginBottom:4}}>{label}</small><strong style={{wordBreak:'break-word'}}>{value}</strong></div>}
function tvLabel(s){return s==='pending'?'🟠 En attente':s==='active'?'🟢 Active':s==='rejected'?'🔴 Refusée':s==='paused'?'⏸️ En pause':'⚫ Terminée'}
function Stat({label,value}){return <div style={cardStyle}><div style={{fontSize:13,color:'#667085',marginBottom:7}}>{label}</div><div style={{fontSize:28,fontWeight:800}}>{value}</div></div>}
const pageStyle={minHeight:'100vh',background:'#f4f7fb',padding:24,fontFamily:'Arial, sans-serif',color:'#172033'},cardStyle={background:'#fff',borderRadius:16,padding:20,boxShadow:'0 4px 18px rgba(16,24,40,.06)'},thStyle={textAlign:'left',padding:'12px 10px',borderBottom:'1px solid #eaecf0',color:'#667085',fontSize:13},tdStyle={padding:'14px 10px',borderBottom:'1px solid #f2f4f7',fontSize:14}
function buttonStyle(background){return{border:0,borderRadius:10,padding:'9px 12px',background,color:'#fff',fontWeight:700,cursor:'pointer'}}
