'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'

export default function AdminPage() {
  const [authChecked, setAuthChecked] = useState(false), [isAdmin, setIsAdmin] = useState(false), [loading, setLoading] = useState(true)
  const [actionBusy, setActionBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [boutiques, setBoutiques] = useState([]), [subscriptions, setSubscriptions] = useState([]), [tvAds, setTvAds] = useState([])

  async function verifyAdmin() { const { data, error: authError } = await supabase.auth.getUser(); const admin = !authError && data?.user?.app_metadata?.role === 'admin'; setIsAdmin(admin); setAuthChecked(true); return admin }
  async function loadAdminData() {
    setLoading(true); setError(''); const admin = await verifyAdmin(); if (!admin) { setLoading(false); return }
    const [b,s,a] = await Promise.all([
      supabase.from('boutiques').select('id,name,plan,is_live,created_at').order('created_at',{ascending:false}),
      supabase.from('subscriptions').select('id,boutique_id,plan,amount_cfa,status,created_at').order('created_at',{ascending:false}),
      supabase.from('market_tv_ads').select('id,boutique_id,title,description,media_url,media_type,duration_seconds,status,starts_at,ends_at,created_at').order('created_at',{ascending:false})
    ])
    if(b.error||s.error||a.error)setError(b.error?.message||s.error?.message||a.error?.message||'Erreur de chargement'); else {setBoutiques(b.data||[]);setSubscriptions(s.data||[]);setTvAds(a.data||[])} setLoading(false)
  }
  useEffect(()=>{loadAdminData()},[])
  const subscriptionsByBoutique=useMemo(()=>{const m=new Map();for(const x of subscriptions)if(!m.has(x.boutique_id))m.set(x.boutique_id,x);return m},[subscriptions])
  const boutiquesById=useMemo(()=>new Map(boutiques.map(b=>[b.id,b])),[boutiques])
  const pendingCount=subscriptions.filter(x=>x.status==='pending').length, liveCount=boutiques.filter(x=>x.is_live).length, pendingTv=tvAds.filter(x=>x.status==='pending').length

  async function setBoutiqueLive(id,isLive,msg){setActionBusy(`boutique-${id}`);setError('');setNotice('');const{error:e}=await supabase.from('boutiques').update({is_live:isLive}).eq('id',id);if(e)setError(e.message);else{setNotice(msg);await loadAdminData()}setActionBusy('')}
  async function approveSubscription(subscription,boutiqueId){setActionBusy(`subscription-${subscription.id}`);setError('');setNotice('');const{error:e}=await supabase.from('subscriptions').update({status:'approved'}).eq('id',subscription.id);if(e){setError(e.message);setActionBusy('');return}const{error:b}=await supabase.from('boutiques').update({is_live:true}).eq('id',boutiqueId);if(b)setError(b.message);else{setNotice('Paiement approuvé et boutique activée.');await loadAdminData()}setActionBusy('')}
  async function rejectSubscription(subscription,boutiqueId){setActionBusy(`subscription-${subscription.id}`);setError('');setNotice('');const{error:e}=await supabase.from('subscriptions').update({status:'rejected'}).eq('id',subscription.id);if(e){setError(e.message);setActionBusy('');return}const{error:b}=await supabase.from('boutiques').update({is_live:false}).eq('id',boutiqueId);if(b)setError(b.message);else{setNotice('Paiement refusé et boutique désactivée.');await loadAdminData()}setActionBusy('')}
  async function setTvStatus(ad,status){setActionBusy(`tv-${ad.id}`);setError('');setNotice('');const patch={status};if(status==='active'&&!ad.starts_at)patch.starts_at=new Date().toISOString();if(status==='ended')patch.ends_at=new Date().toISOString();const{error:e}=await supabase.from('market_tv_ads').update(patch).eq('id',ad.id);if(e)setError(e.message);else{setNotice(status==='active'?'Publicité TV approuvée et activée.':status==='rejected'?'Publicité TV refusée.':status==='paused'?'Publicité TV mise en pause.':'Publicité TV terminée.');await loadAdminData()}setActionBusy('')}

  if(!authChecked||loading)return <main style={pageStyle}><div style={cardStyle}>Vérification Admin...</div></main>
  if(!isAdmin)return <main style={pageStyle}><div style={{...cardStyle,maxWidth:560,margin:'80px auto',textAlign:'center'}}><h1 style={{marginTop:0}}>Accès Admin protégé</h1><p style={{color:'#667085'}}>Cette page est réservée au compte administrateur WakhReek.</p><a href="/" style={{color:'#0066ff',fontWeight:700}}>Retour à WakhReek</a></div></main>

  return <main style={pageStyle}><div style={{maxWidth:1180,margin:'0 auto'}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap',marginBottom:24}}><div><h1 style={{margin:0,fontSize:30}}>WakhReek Admin</h1><p style={{margin:'6px 0 0',color:'#667085'}}>Gestion protégée des boutiques, abonnements et WakhReek TV</p></div><button onClick={loadAdminData} style={buttonStyle('#0066ff')}>Actualiser</button></div>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14,marginBottom:22}}><Stat label="Boutiques" value={boutiques.length}/><Stat label="Boutiques actives" value={liveCount}/><Stat label="Paiements en attente" value={pendingCount}/><Stat label="Publicités TV en attente" value={pendingTv}/></section>
    {notice&&<div style={{...cardStyle,border:'1px solid #12b76a',color:'#027a48',marginBottom:18}}>{notice}</div>}{error&&<div style={{...cardStyle,border:'1px solid #f04438',color:'#b42318',marginBottom:18}}>Erreur: {error}</div>}

    <section style={{...cardStyle,marginBottom:20}}><h2 style={{marginTop:0}}>📺 Division Publicité — WakhReek TV</h2><p style={{color:'#667085'}}>Les vidéos commerçants restent en attente jusqu’à validation Admin. Format obligatoire : vidéo de 30 à 45 secondes.</p>
      {tvAds.length===0?<p style={{color:'#667085'}}>Aucune publicité TV pour le moment.</p>:<div style={{display:'grid',gap:14}}>{tvAds.map(ad=>{const busy=actionBusy===`tv-${ad.id}`,shop=boutiquesById.get(ad.boutique_id);return <article key={ad.id} style={{border:'1px solid #eaecf0',borderRadius:14,padding:14,display:'grid',gridTemplateColumns:'minmax(240px,360px) 1fr',gap:16}}><video src={ad.media_url} controls preload="metadata" style={{width:'100%',maxHeight:230,background:'#000',borderRadius:10}}/><div><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><strong style={{fontSize:18}}>{ad.title}</strong><div style={{color:'#667085',marginTop:4}}>{shop?.name||'Boutique'} • {Number(ad.duration_seconds).toFixed(1)} s</div></div><b>{tvLabel(ad.status)}</b></div>{ad.description&&<p>{ad.description}</p>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{ad.status!=='active'&&<button disabled={busy} onClick={()=>setTvStatus(ad,'active')} style={buttonStyle('#12b76a')}>{busy?'...':'Approuver / Activer'}</button>}{ad.status!=='rejected'&&ad.status!=='ended'&&<button disabled={busy} onClick={()=>setTvStatus(ad,'rejected')} style={buttonStyle('#d92d20')}>{busy?'...':'Refuser'}</button>}{ad.status==='active'&&<button disabled={busy} onClick={()=>setTvStatus(ad,'paused')} style={buttonStyle('#f79009')}>Pause</button>}{(ad.status==='active'||ad.status==='paused')&&<button disabled={busy} onClick={()=>setTvStatus(ad,'ended')} style={buttonStyle('#667085')}>Terminer</button>}</div></div></article>})}</div>}
    </section>

    <section style={cardStyle}><h2 style={{marginTop:0}}>Boutiques</h2>{boutiques.length===0?<p style={{color:'#667085'}}>Aucune boutique pour le moment.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:980}}><thead><tr>{['Boutique','Plan','Paiement','Montant','État','Créée le','Actions Admin'].map(t=><th key={t} style={thStyle}>{t}</th>)}</tr></thead><tbody>{boutiques.map(b=>{const s=subscriptionsByBoutique.get(b.id),bb=actionBusy===`boutique-${b.id}`,bs=s&&actionBusy===`subscription-${s.id}`,busy=bb||bs;return <tr key={b.id}><td style={tdStyle}><strong>{b.name}</strong></td><td style={tdStyle}>{b.plan||'-'}</td><td style={tdStyle}>{s?.status||'Aucun paiement'}</td><td style={tdStyle}>{s?.amount_cfa!=null?`${s.amount_cfa} CFA`:'-'}</td><td style={tdStyle}>{b.is_live?'Active':'Inactive'}</td><td style={tdStyle}>{b.created_at?new Date(b.created_at).toLocaleDateString('fr-FR'):'-'}</td><td style={{...tdStyle,minWidth:290}}><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{!b.is_live&&<button disabled={busy} onClick={()=>setBoutiqueLive(b.id,true,'Boutique activée gratuitement par Admin.')} style={buttonStyle('#7f56d9')}>{bb?'...':'Activer gratuit'}</button>}{b.is_live&&<button disabled={busy} onClick={()=>setBoutiqueLive(b.id,false,'Boutique désactivée par Admin.')} style={buttonStyle('#667085')}>{bb?'...':'Désactiver'}</button>}{s?.status==='pending'&&<><button disabled={busy} onClick={()=>approveSubscription(s,b.id)} style={buttonStyle('#12b76a')}>{bs?'...':'Approuver'}</button><button disabled={busy} onClick={()=>rejectSubscription(s,b.id)} style={buttonStyle('#d92d20')}>{bs?'...':'Refuser'}</button></>}</div></td></tr>})}</tbody></table></div>}</section>
  </div><style jsx>{`@media(max-width:720px){article{grid-template-columns:1fr!important}}`}</style></main>
}
function tvLabel(s){return s==='pending'?'🟠 En attente':s==='active'?'🟢 Active':s==='rejected'?'🔴 Refusée':s==='paused'?'⏸️ En pause':'⚫ Terminée'}
function Stat({label,value}){return <div style={cardStyle}><div style={{fontSize:13,color:'#667085',marginBottom:7}}>{label}</div><div style={{fontSize:28,fontWeight:800}}>{value}</div></div>}
const pageStyle={minHeight:'100vh',background:'#f4f7fb',padding:24,fontFamily:'Arial, sans-serif',color:'#172033'},cardStyle={background:'#fff',borderRadius:16,padding:20,boxShadow:'0 4px 18px rgba(16,24,40,.06)'},thStyle={textAlign:'left',padding:'12px 10px',borderBottom:'1px solid #eaecf0',color:'#667085',fontSize:13},tdStyle={padding:'14px 10px',borderBottom:'1px solid #f2f4f7',fontSize:14}
function buttonStyle(background){return{border:0,borderRadius:10,padding:'9px 12px',background,color:'#fff',fontWeight:700,cursor:'pointer'}}
