'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../../lib/supabase'

export default function AdminAI(){
 const[prompt,setPrompt]=useState(''),[size,setSize]=useState('square_hd'),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(''),[authChecked,setAuthChecked]=useState(false),[isAdmin,setIsAdmin]=useState(false)
 const[mode,setMode]=useState('image'),[duration,setDuration]=useState('5'),[aspect,setAspect]=useState('16:9'),[audio,setAudio]=useState(false),[videoResult,setVideoResult]=useState(null),[videoStatus,setVideoStatus]=useState('')
 useEffect(()=>{verifyAdmin()},[])
 async function verifyAdmin(){let{data:{session}}=await supabase.auth.getSession();if(session){const refreshed=await supabase.auth.refreshSession();if(refreshed.data?.session)session=refreshed.data.session}const{data,error:e}=await supabase.auth.getUser(session?.access_token);setIsAdmin(!e&&data?.user?.app_metadata?.role==='admin');setAuthChecked(true)}
 async function sessionToken(){let{data:{session}}=await supabase.auth.getSession();if(session){const refreshed=await supabase.auth.refreshSession();if(refreshed.data?.session)session=refreshed.data.session}return session?.access_token||''}
 async function generateImage(){setBusy(true);setError('');setResult(null);const token=await sessionToken();if(!token){setError('جلسة الإدارة غير متوفرة. ارجع إلى WakhReek وسجّل الدخول.');setBusy(false);return}const r=await fetch('/api/admin/ai/image',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({prompt,image_size:size})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(typeof d.error==='string'?d.error:JSON.stringify(d.error||'Generation failed'));else setResult(d);setBusy(false)}
 async function generateVideo(){setBusy(true);setError('');setVideoResult(null);setVideoStatus('إرسال طلب الفيديو...');const token=await sessionToken();if(!token){setError('جلسة الإدارة غير متوفرة.');setBusy(false);return}const r=await fetch('/api/admin/ai/video',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({prompt,duration,aspect_ratio:aspect,generate_audio:audio})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.request_id){setError(typeof d.error==='string'?d.error:'Video generation failed');setVideoStatus('');setBusy(false);return}setVideoStatus('الفيديو قيد التوليد...');for(let i=0;i<60;i++){await new Promise(x=>setTimeout(x,5000));const sr=await fetch(`/api/admin/ai/video?request_id=${encodeURIComponent(d.request_id)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const sd=await sr.json().catch(()=>({}));if(!sr.ok){setError(typeof sd.error==='string'?sd.error:'Video status failed');setVideoStatus('');setBusy(false);return}if(sd.status==='COMPLETED'){setVideoResult(sd);setVideoStatus('');setBusy(false);return}setVideoStatus(sd.queue_position!=null?`في قائمة الانتظار: ${sd.queue_position}`:'الفيديو قيد التوليد...')}setError('استغرق التوليد وقتًا أطول من المتوقع. أعد المحاولة بعد قليل.');setVideoStatus('');setBusy(false)}
 if(!authChecked)return <main className="studio"><section>جاري التحقق من صلاحية الإدارة...</section><Style/></main>
 if(!isAdmin)return <main className="studio"><section style={{textAlign:'center'}}><h1>Admin فقط</h1><p>هذه الأداة محمية ومخصصة لإدارة WakhReek.</p><button onClick={()=>location.href='/admin'}>← Admin</button></section><Style/></main>
 return <main className="studio"><header><div><h1>WakhReek AI Studio</h1><p>توليد الصور والفيديو للإدارة</p></div><button className="back" onClick={()=>location.href='/admin'}>← Admin</button></header><section><div className="tabs"><button className={mode==='image'?'active':''} onClick={()=>{setMode('image');setError('')}}>🖼️ صورة</button><button className={mode==='video'?'active':''} onClick={()=>{setMode('video');setError('')}}>🎬 فيديو</button></div><label>الوصف / Prompt</label><textarea rows="7" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={mode==='video'?'مثال: إعلان سينمائي لمنتج مغربي، حركة كاميرا بطيئة، إضاءة احترافية...':'مثال: إعلان احترافي لمنتج مغربي، إضاءة استوديو، خلفية نظيفة...'}/>{mode==='image'?<div className="row"><label>المقاس<select value={size} onChange={e=>setSize(e.target.value)}><option value="square_hd">مربع HD</option><option value="portrait_4_3">عمودي 4:3</option><option value="portrait_16_9">عمودي 16:9</option><option value="landscape_4_3">أفقي 4:3</option><option value="landscape_16_9">أفقي 16:9</option></select></label><button disabled={busy||prompt.trim().length<3} onClick={generateImage}>{busy?'جاري التوليد...':'✨ توليد الصورة'}</button></div>:<><div className="videoOptions"><label>المدة<select value={duration} onChange={e=>setDuration(e.target.value)}><option value="5">5 ثوان</option><option value="10">10 ثوان</option></select></label><label>الشكل<select value={aspect} onChange={e=>setAspect(e.target.value)}><option value="16:9">16:9 أفقي</option><option value="9:16">9:16 عمودي</option><option value="1:1">1:1 مربع</option></select></label><label className="check"><input type="checkbox" checked={audio} onChange={e=>setAudio(e.target.checked)}/> توليد الصوت</label></div><button className="generateVideo" disabled={busy||prompt.trim().length<3} onClick={generateVideo}>{busy?'⏳ جاري التوليد...':'🎬 توليد الفيديو'}</button>{videoStatus&&<p className="progress">{videoStatus}</p>}</>}{error&&<p className="err">{error}</p>}</section>{mode==='image'&&result?.image?.url&&<section className="out"><h2>النتيجة</h2><img src={result.image.url} alt="AI result"/><div className="meta">Model: {result.model}{result.seed!==undefined?` · Seed: ${result.seed}`:''}</div><a href={result.image.url} target="_blank" rel="noreferrer">فتح الصورة الأصلية</a></section>}{mode==='video'&&videoResult?.video?.url&&<section className="out"><h2>الفيديو جاهز</h2><video src={videoResult.video.url} controls playsInline/><div className="meta">Model: {videoResult.model}</div><a href={videoResult.video.url} target="_blank" rel="noreferrer">فتح الفيديو الأصلي</a></section>}<Style/></main>
}
function Style(){return <style jsx global>{`.studio{min-height:100vh;background:#f5f7fb;padding:28px;font-family:Arial;color:#172033}.studio header,.studio section{max-width:1000px;margin:0 auto 16px}.studio header{display:flex;justify-content:space-between;align-items:center}.studio section{background:#fff;border:1px solid #e2e7ef;border-radius:16px;padding:20px}.studio textarea,.studio select{width:100%;box-sizing:border-box;margin-top:7px;padding:12px;border:1px solid #ccd5e2;border-radius:10px;font:inherit}.studio textarea{resize:vertical}.studio .row{display:grid;grid-template-columns:1fr 220px;gap:14px;align-items:end;margin-top:14px}.studio button,.studio .out a{border:0;border-radius:10px;padding:12px 16px;background:#0868d7;color:white;font-weight:800;text-decoration:none;text-align:center;cursor:pointer}.studio .back{background:#172033}.studio button:disabled{opacity:.55;cursor:not-allowed}.studio .err{background:#ffe8e8;color:#a00000;padding:12px;border-radius:9px}.studio .progress{background:#eef6ff;color:#0759b4;padding:12px;border-radius:9px}.studio .out{text-align:center}.studio .out img,.studio .out video{max-width:100%;max-height:720px;border-radius:12px}.studio .meta{margin:10px;color:#667085}.studio .out a{display:inline-block;margin-top:8px}.studio .tabs{display:flex;gap:8px;margin-bottom:18px}.studio .tabs button{background:#e8edf5;color:#172033}.studio .tabs button.active{background:#0868d7;color:#fff}.studio .videoOptions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;align-items:end;margin-top:14px}.studio .check{display:flex;gap:8px;align-items:center;padding-bottom:12px}.studio .check input{width:auto}.studio .generateVideo{width:100%;margin-top:16px;padding:15px}@media(max-width:650px){.studio{padding:14px}.studio .row,.studio .videoOptions{grid-template-columns:1fr}.studio header{gap:10px}.studio header h1{font-size:22px}}`}</style>}
