'use client'

import Link from 'next/link'
import styles from './download.module.css'
import {useI18n} from '../../components/I18nProvider'

const APK_URL='/WakhReek-Android-1.0.0.apk'
const SHOW_APK_DOWNLOAD=false // Keep APK available, but hide its button until Google Play
const copy={
 fr:{journeyTitle:'Bienvenue sur WakhReek',journeyText:'Découvrez librement WakhReek Marché, ses boutiques et ses produits. Pour communiquer avec les boutiques, rejoindre WakhReek Social et utiliser Communication, créez gratuitement votre compte.',socialBadge:'WAKHREEK SOCIAL',socialTitle:'Découvrez WakhReek Social',socialText:'Personnes, vidéos, boutiques et produits : découvrez la communauté avant de créer votre compte.',socialCta:'Découvrir WakhReek',install80:'Comment installer WakhReek ?',install80Text:'Regardez la vidéo 80 pour découvrir, étape par étape, comment télécharger, installer et ouvrir WakhReek sur votre téléphone.',open:'Ouvrir WakhReek',badge:'APPLICATION OFFICIELLE ANDROID',title:'WakhReek sur votre téléphone',lead:'Boutiques, messagerie, notes vocales et appels audio/vidéo dans une seule application.',soon:'APK officiel en préparation',download:'Télécharger WakhReek APK',web:'S’inscrire',version:'Android 1.0.0 • Version officielle',android:'Android',official:'Téléchargement officiel : wakhreek.com',features:['💬 Messages','🎙️ Audio','📞 Appels','🎥 Vidéo'],install:'INSTALLATION',how:'Comment installer WakhReek',simple:'Une installation simple, depuis le site officiel.',steps:[['Télécharger','Appuyez sur « Télécharger WakhReek APK » depuis cette page officielle.'],['Autoriser l’installation','Si Android le demande, autorisez votre navigateur à installer cette application.'],['Installer','Ouvrez le fichier téléchargé puis appuyez sur « Installer ».'],['Ouvrir WakhReek','Connectez-vous et utilisez la messagerie, l’audio et les appels.']],security:'🔒 Sécurité',securityText:'Téléchargez WakhReek uniquement depuis wakhreek.com. Il n’est pas nécessaire de désactiver Play Protect.',guide:'GUIDE VIDÉO',videoTitle:'Une vidéo montrera chaque étape',videoText:'Nous ajouterons ici une démonstration courte : téléchargement, autorisation Android, installation et première ouverture.',video:'Guide d’installation WakhReek',videoSoon:'Vidéo bientôt disponible',app:'Application officielle Android',back:'Retour à l’accueil'},
 ar:{journeyTitle:'مرحباً بك في WakhReek',journeyText:'اكتشف WakhReek Marché بحرية وتجوّل بين المتاجر والمنتجات. وللتواصل مع المتاجر والانضمام إلى WakhReek Social واستخدام Communication، أنشئ حسابك مجاناً.',socialBadge:'WAKHREEK SOCIAL',socialTitle:'اكتشف WakhReek Social',socialText:'أشخاص وفيديوهات ومتاجر ومنتجات: اكتشف مجتمع WakhReek قبل إنشاء حسابك.',socialCta:'اكتشف WakhReek',install80:'كيف تثبت WakhReek؟',install80Text:'شاهد فيديو 80 لتتعرف خطوة بخطوة على كيفية تحميل WakhReek وتثبيته وفتحه على هاتفك.',open:'فتح WakhReek',badge:'تطبيق WakhReek الرسمي لأندرويد',title:'WakhReek على هاتفك',lead:'المتاجر والرسائل والمقاطع الصوتية ومكالمات الصوت والفيديو في تطبيق واحد.',soon:'النسخة الرسمية APK قيد التجهيز',download:'تحميل WakhReek APK',web:'إنشاء حساب',version:'Android 1.0.0 • النسخة الرسمية',android:'أندرويد',official:'التحميل الرسمي: wakhreek.com',features:['💬 الرسائل','🎙️ الصوت','📞 المكالمات','🎥 الفيديو'],install:'التثبيت',how:'كيفية تثبيت WakhReek',simple:'تثبيت بسيط مباشرة من الموقع الرسمي.',steps:[['التحميل','اضغط «تحميل WakhReek APK» من هذه الصفحة الرسمية.'],['السماح بالتثبيت','إذا طلب Android ذلك، اسمح للمتصفح بتثبيت التطبيق.'],['التثبيت','افتح الملف الذي تم تنزيله ثم اضغط «تثبيت».'],['فتح WakhReek','سجّل الدخول واستعمل الرسائل والصوت والمكالمات.']],security:'🔒 الأمان',securityText:'حمّل WakhReek فقط من wakhreek.com. لا حاجة لتعطيل Play Protect.',guide:'فيديو الشرح',videoTitle:'فيديو يشرح كل مراحل التثبيت',videoText:'سنضع هنا شرحًا قصيرًا للتحميل والسماح بالتثبيت والتثبيت وأول تشغيل.',video:'دليل تثبيت WakhReek',videoSoon:'الفيديو قريبًا',app:'تطبيق Android الرسمي',back:'العودة للرئيسية'},
 en:{journeyTitle:'Welcome to WakhReek',journeyText:'Explore WakhReek Marché freely and discover its shops and products. To contact shops, join WakhReek Social and use Communication, create your free account.',socialBadge:'WAKHREEK SOCIAL',socialTitle:'Discover WakhReek Social',socialText:'People, videos, shops and products: discover the community before creating your account.',socialCta:'Discover WakhReek',install80:'How to install WakhReek?',install80Text:'Watch video 80 to learn, step by step, how to download, install and open WakhReek on your phone.',open:'Open WakhReek',badge:'OFFICIAL ANDROID APP',title:'WakhReek on your phone',lead:'Shops, messaging, voice notes and audio/video calls in one application.',soon:'Official APK in preparation',download:'Download WakhReek APK',web:'Sign up',version:'Android 1.0.0 • Official release',android:'Android',official:'Official download: wakhreek.com',features:['💬 Messages','🎙️ Audio','📞 Calls','🎥 Video'],install:'INSTALLATION',how:'How to install WakhReek',simple:'Simple installation from the official website.',steps:[['Download','Tap “Download WakhReek APK” on this official page.'],['Allow installation','If Android asks, allow your browser to install this application.'],['Install','Open the downloaded file and tap “Install”.'],['Open WakhReek','Sign in and use messaging, audio and calls.']],security:'🔒 Security',securityText:'Download WakhReek only from wakhreek.com. You do not need to disable Play Protect.',guide:'VIDEO GUIDE',videoTitle:'A video will show every step',videoText:'A short guide will show download, Android permission, installation and first launch.',video:'WakhReek installation guide',videoSoon:'Video coming soon',app:'Official Android application',back:'Back to home'},
 pt:{journeyTitle:'Bem-vindo ao WakhReek',journeyText:'Explore livremente o WakhReek Marché e descubra as suas lojas e produtos. Para contactar lojas, entrar no WakhReek Social e usar Communication, crie gratuitamente a sua conta.',socialBadge:'WAKHREEK SOCIAL',socialTitle:'Descubra o WakhReek Social',socialText:'Pessoas, vídeos, lojas e produtos: descubra a comunidade antes de criar a sua conta.',socialCta:'Descobrir WakhReek',install80:'Como instalar o WakhReek?',install80Text:'Veja o vídeo 80 para aprender, passo a passo, como baixar, instalar e abrir o WakhReek no seu telefone.',open:'Abrir WakhReek',badge:'APLICAÇÃO ANDROID OFICIAL',title:'WakhReek no seu telefone',lead:'Lojas, mensagens, notas de voz e chamadas de áudio/vídeo numa só aplicação.',soon:'APK oficial em preparação',download:'Baixar WakhReek APK',web:'Criar conta',version:'Android 1.0.0 • Versão oficial',android:'Android',official:'Download oficial: wakhreek.com',features:['💬 Mensagens','🎙️ Áudio','📞 Chamadas','🎥 Vídeo'],install:'INSTALAÇÃO',how:'Como instalar WakhReek',simple:'Instalação simples a partir do site oficial.',steps:[['Baixar','Toque em “Baixar WakhReek APK” nesta página oficial.'],['Permitir instalação','Se o Android pedir, permita que o navegador instale esta aplicação.'],['Instalar','Abra o ficheiro baixado e toque em “Instalar”.'],['Abrir WakhReek','Entre e use mensagens, áudio e chamadas.']],security:'🔒 Segurança',securityText:'Baixe WakhReek apenas em wakhreek.com. Não é necessário desativar o Play Protect.',guide:'GUIA EM VÍDEO',videoTitle:'Um vídeo mostrará cada etapa',videoText:'Adicionaremos uma demonstração curta do download, autorização, instalação e primeira abertura.',video:'Guia de instalação WakhReek',videoSoon:'Vídeo em breve',app:'Aplicação Android oficial',back:'Voltar ao início'}
}

export default function DownloadContent(){
 const{language}=useI18n();const c=copy[language]||copy.en;const releaseReady=Boolean(APK_URL)
 return <main className={styles.page}>
  <header className={styles.header}><Link href="/market" className={styles.brand} aria-label="WakhReek"><img src="/wakhreek-192-v2.png" alt="WakhReek"/><span>WakhReek</span></Link><nav><Link href="/market">{c.open}</Link></nav></header>
  <section className={styles.hero}><div className={styles.heroText}><span className={styles.badge}>{c.badge}</span><h1>{c.title}</h1><p className={styles.lead}>{c.lead}</p><div className={styles.actions}>{SHOW_APK_DOWNLOAD && (releaseReady?<a className={styles.primary} href={APK_URL} download>{c.download}</a>:<span className={`${styles.primary} ${styles.disabled}`} aria-disabled="true">{c.soon}</span>)}<Link className={styles.secondary} href="/inscription">{c.web}</Link></div><div className={styles.releaseInfo}><span>✓ {c.version}</span><span>✓ {c.android}</span><span>✓ {c.official}</span></div></div><div className={styles.phoneCard}><div className={styles.phoneTop}></div><img src="/wakhreek-512-v2.png" alt="WakhReek"/><h2>WakhReek</h2><p>Boutiques • Messagerie • Communauté</p><div className={styles.features}>{c.features.map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className={styles.install}><div className={styles.sectionTitle}><span>{c.install}</span><h2>{c.how}</h2><p>{c.simple}</p></div><div className={styles.showcaseGrid}><article className={styles.showcaseCard}><div className={styles.journeyText}><h3>{c.journeyTitle}</h3><p>{c.journeyText}</p><Link className={styles.primary} href="/inscription">{c.web}</Link></div><Link href="/market" className={styles.phoneCard+" "+styles.marketPhone}><div className={styles.phoneTop}></div><img src={'/'+encodeURIComponent('Screenshot_20260923-221129.png')} alt="WakhReek Marché"/></Link></article></div><div className={styles.securityNote}><strong>{c.security}</strong><p>{c.securityText}</p></div></section>
  <section className={styles.videoSection}><div className={styles.socialPreview}><span className={styles.badge}>{c.socialBadge}</span><h2>{c.socialTitle}</h2><p>{c.socialText}</p><Link className={styles.primary} href="/market">{c.socialCta}</Link></div><div><div className={styles.videoPlaceholder}><video controls playsInline preload="metadata" src="/Ma%20vid%C3%A9o-80.mp4" /></div><div className={styles.videoCaption}><h3>{c.install80}</h3><p>{c.install80Text}</p></div></div></section>
  <footer className={styles.footer}><img src="/wakhreek-192-v2.png" alt=""/><div><strong>WakhReek</strong><span>{c.app}</span></div><Link href="/market">{c.back}</Link></footer>
 </main>
}
