'use client'

import Link from 'next/link'
import styles from './download.module.css'
import {useI18n} from '../../components/I18nProvider'

const APK_URL='/WakhReek-Android-1.0.0.apk'
const copy={
 fr:{open:'Ouvrir WakhReek',badge:'APPLICATION OFFICIELLE ANDROID',title:'WakhReek sur votre téléphone',lead:'Boutiques, messagerie, notes vocales et appels audio/vidéo dans une seule application.',soon:'APK officiel en préparation',download:'Télécharger WakhReek APK',web:'Utiliser la version Web',version:'Android 1.0.0 • Version officielle',android:'Android',official:'Téléchargement officiel : wakhreek.com',features:['💬 Messages','🎙️ Audio','📞 Appels','🎥 Vidéo'],install:'INSTALLATION',how:'Comment installer WakhReek',simple:'Une installation simple, depuis le site officiel.',steps:[['Télécharger','Appuyez sur « Télécharger WakhReek APK » depuis cette page officielle.'],['Autoriser l’installation','Si Android le demande, autorisez votre navigateur à installer cette application.'],['Installer','Ouvrez le fichier téléchargé puis appuyez sur « Installer ».'],['Ouvrir WakhReek','Connectez-vous et utilisez la messagerie, l’audio et les appels.']],security:'🔒 Sécurité',securityText:'Téléchargez WakhReek uniquement depuis wakhreek.com. Il n’est pas nécessaire de désactiver Play Protect.',guide:'GUIDE VIDÉO',videoTitle:'Une vidéo montrera chaque étape',videoText:'Nous ajouterons ici une démonstration courte : téléchargement, autorisation Android, installation et première ouverture.',video:'Guide d’installation WakhReek',videoSoon:'Vidéo bientôt disponible',app:'Application officielle Android',back:'Retour à l’accueil'},
 ar:{open:'فتح WakhReek',badge:'تطبيق WakhReek الرسمي لأندرويد',title:'WakhReek على هاتفك',lead:'المتاجر والرسائل والمقاطع الصوتية ومكالمات الصوت والفيديو في تطبيق واحد.',soon:'النسخة الرسمية APK قيد التجهيز',download:'تحميل WakhReek APK',web:'استخدام نسخة الويب',version:'Android 1.0.0 • النسخة الرسمية',android:'أندرويد',official:'التحميل الرسمي: wakhreek.com',features:['💬 الرسائل','🎙️ الصوت','📞 المكالمات','🎥 الفيديو'],install:'التثبيت',how:'كيفية تثبيت WakhReek',simple:'تثبيت بسيط مباشرة من الموقع الرسمي.',steps:[['التحميل','اضغط «تحميل WakhReek APK» من هذه الصفحة الرسمية.'],['السماح بالتثبيت','إذا طلب Android ذلك، اسمح للمتصفح بتثبيت التطبيق.'],['التثبيت','افتح الملف الذي تم تنزيله ثم اضغط «تثبيت».'],['فتح WakhReek','سجّل الدخول واستعمل الرسائل والصوت والمكالمات.']],security:'🔒 الأمان',securityText:'حمّل WakhReek فقط من wakhreek.com. لا حاجة لتعطيل Play Protect.',guide:'فيديو الشرح',videoTitle:'فيديو يشرح كل مراحل التثبيت',videoText:'سنضع هنا شرحًا قصيرًا للتحميل والسماح بالتثبيت والتثبيت وأول تشغيل.',video:'دليل تثبيت WakhReek',videoSoon:'الفيديو قريبًا',app:'تطبيق Android الرسمي',back:'العودة للرئيسية'},
 en:{open:'Open WakhReek',badge:'OFFICIAL ANDROID APP',title:'WakhReek on your phone',lead:'Shops, messaging, voice notes and audio/video calls in one application.',soon:'Official APK in preparation',download:'Download WakhReek APK',web:'Use the Web version',version:'Android 1.0.0 • Official release',android:'Android',official:'Official download: wakhreek.com',features:['💬 Messages','🎙️ Audio','📞 Calls','🎥 Video'],install:'INSTALLATION',how:'How to install WakhReek',simple:'Simple installation from the official website.',steps:[['Download','Tap “Download WakhReek APK” on this official page.'],['Allow installation','If Android asks, allow your browser to install this application.'],['Install','Open the downloaded file and tap “Install”.'],['Open WakhReek','Sign in and use messaging, audio and calls.']],security:'🔒 Security',securityText:'Download WakhReek only from wakhreek.com. You do not need to disable Play Protect.',guide:'VIDEO GUIDE',videoTitle:'A video will show every step',videoText:'A short guide will show download, Android permission, installation and first launch.',video:'WakhReek installation guide',videoSoon:'Video coming soon',app:'Official Android application',back:'Back to home'},
 pt:{open:'Abrir WakhReek',badge:'APLICAÇÃO ANDROID OFICIAL',title:'WakhReek no seu telefone',lead:'Lojas, mensagens, notas de voz e chamadas de áudio/vídeo numa só aplicação.',soon:'APK oficial em preparação',download:'Baixar WakhReek APK',web:'Usar a versão Web',version:'Android 1.0.0 • Versão oficial',android:'Android',official:'Download oficial: wakhreek.com',features:['💬 Mensagens','🎙️ Áudio','📞 Chamadas','🎥 Vídeo'],install:'INSTALAÇÃO',how:'Como instalar WakhReek',simple:'Instalação simples a partir do site oficial.',steps:[['Baixar','Toque em “Baixar WakhReek APK” nesta página oficial.'],['Permitir instalação','Se o Android pedir, permita que o navegador instale esta aplicação.'],['Instalar','Abra o ficheiro baixado e toque em “Instalar”.'],['Abrir WakhReek','Entre e use mensagens, áudio e chamadas.']],security:'🔒 Segurança',securityText:'Baixe WakhReek apenas em wakhreek.com. Não é necessário desativar o Play Protect.',guide:'GUIA EM VÍDEO',videoTitle:'Um vídeo mostrará cada etapa',videoText:'Adicionaremos uma demonstração curta do download, autorização, instalação e primeira abertura.',video:'Guia de instalação WakhReek',videoSoon:'Vídeo em breve',app:'Aplicação Android oficial',back:'Voltar ao início'}
}

export default function DownloadContent(){
 const{language}=useI18n();const c=copy[language]||copy.en;const releaseReady=Boolean(APK_URL)
 return <main className={styles.page}>
  <header className={styles.header}><Link href="/" className={styles.brand} aria-label="WakhReek"><img src="/wakhreek-192-v2.png" alt="WakhReek"/><span>WakhReek</span></Link><nav><Link href="/communication">{c.open}</Link></nav></header>
  <section className={styles.hero}><div className={styles.heroText}><span className={styles.badge}>{c.badge}</span><h1>{c.title}</h1><p className={styles.lead}>{c.lead}</p><div className={styles.actions}>{releaseReady?<a className={styles.primary} href={APK_URL} download>{c.download}</a>:<span className={`${styles.primary} ${styles.disabled}`} aria-disabled="true">{c.soon}</span>}<Link className={styles.secondary} href="/communication">{c.web}</Link></div><div className={styles.releaseInfo}><span>✓ {c.version}</span><span>✓ {c.android}</span><span>✓ {c.official}</span></div></div><div className={styles.phoneCard}><div className={styles.phoneTop}></div><img src="/wakhreek-512-v2.png" alt="WakhReek"/><h2>WakhReek</h2><p>Boutiques • Messagerie • Communauté</p><div className={styles.features}>{c.features.map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className={styles.install}><div className={styles.sectionTitle}><span>{c.install}</span><h2>{c.how}</h2><p>{c.simple}</p></div><div className={styles.steps}>{c.steps.map((s,i)=><article key={s[0]}><b>{i+1}</b><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div><div className={styles.securityNote}><strong>{c.security}</strong><p>{c.securityText}</p></div></section>
  <section className={styles.videoSection}><div><span className={styles.badge}>{c.guide}</span><h2>{c.videoTitle}</h2><p>{c.videoText}</p></div><div className={styles.videoPlaceholder}><video controls playsInline preload="metadata" src="/tutorial-download.mp4" style={{width:'100%',height:'auto',borderRadius:'14px',display:'block'}} /></div></section>
  <footer className={styles.footer}><img src="/wakhreek-192-v2.png" alt=""/><div><strong>WakhReek</strong><span>{c.app}</span></div><Link href="/">{c.back}</Link></footer>
 </main>
}
