'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import AppShell from '../../../components/AppShell'
import { supabase } from '../../../lib/supabase'

export default function MyBoutiquePage(){
 const router=useRouter(); const [user,setUser]=useState(null); const [shop,setShop]=useState(null); const [products,setProducts]=useState([]); const [inquiries,setInquiries]=useState([]); const [form,setForm]=useState({name:'',price:'',category:'',image_url:'',stock:''}); const [notice,setNotice]=useState('');
 async function load(){const {data:a}=await supabase.auth.getUser();const u=a?.user;if(!u){router.push('/');return}setUser(u);const {data:b}=await supabase.from('boutiques').select('*').eq('user_id',u.id).order('created_at',{ascending:false}).limit(1).maybeSingle();setShop(b||null);if(b){const [{data:p},{data:q}]=await Promise.all([supabase.from('products').select('*').eq('boutique_id',b.id).order('created_at',{ascending:false}),supabase.from('market_boutique_inquiries').select('*').eq('boutique_id',b.id).order('created_at',{ascending:false})]);setProducts(p||[]);setInquiries(q||[])}}
 useEffect(()=>{load()},[])
 async function addProduct(e){e.preventDefault();setNotice('');if(!shop?.is_live)return setNotice('La boutique doit être validée et active avant la publication.');if(shop.product_count_limit!=null&&products.length>=shop.product_count_limit)return setNotice(`Limite du plan atteinte: ${shop.product_count_limit} produits.`);const price=Number(form.price);if(!form.name.trim()||!form.category.trim()||!Number.isFinite(price)||price<0)return setNotice('Nom, catégorie et prix valides sont obligatoires.');const payload={boutique_id:shop.id,name:form.name.trim(),category:form.category.trim(),price_cfa:Math.round(price),price_amount:price,currency_code:'XOF',image_url:form.image_url.trim()||null,stock:form.stock===''?null:Number(form.stock)};const {error}=await supabase.from('products').insert(payload);if(error)return setNotice(error.message);setForm({name:'',price:'',category:'',image_url:'',stock:''});setNotice('Produit ajouté.');load()}
 async function removeProduct(id){const {error}=await supabase.from('products').delete().eq('id',id).eq('boutique_id',shop.id);if(error)return setNotice(error.message);load()}
 async function reply(q){const text=prompt('Réponse au client:');if(!text?.trim())return;const {error}=await supabase.from('market_boutique_inquiries').update({reply:text.trim(),status:'replied',replied_at:new Date().toISOString()}).eq('id',q.id);if(error)return setNotice(error.message);load()}
 if(!shop)return <AppShell><main className="wrap"><section className="card"><h2>Ma boutique</h2><p>Aucune boutique trouvée sur ce compte.</p><button onClick={()=>router.push('/market/create')}>Créer une boutique</button></section></main></AppShell>
 return <AppShell><main className="wrap"><header className="top"><div><small>ESPACE VENDEUR WAKHREEK</small><h1>{shop.name}</h1><p>{shop.is_live?'🟢 Boutique active et visible':'🟠 En attente de validation / activation'}</p></div><div className="actions"><button onClick={()=>router.push(`/market/boutique/${shop.id}`)} disabled={!shop.is_live}>Voir ma boutique</button><button onClick={()=>router.push('/market')}>Marché</button></div></header>
 <div className="stats"><div><b>{products.length}</b><span>Produits</span></div><div><b>{shop.product_count_limit??'∞'}</b><span>Limite du plan</span></div><div><b>{inquiries.filter(x=>x.status==='new').length}</b><span>Nouveaux clients</span></div><div><b>{shop.has_ai_agent?'Oui':'Non'}</b><span>Assistant IA</span></div></div>
 <section className="card"><h2>Ajouter un produit</h2><p className="rule">Le vendeur contrôle ses prix et ses produits. Le stock est facultatif. La limite de produits dépend uniquement du plan loué.</p><form onSubmit={addProduct} className="form"><input placeholder="Nom du produit" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Catégorie" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input type="number" min="0" step="1" placeholder="Prix" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input type="number" min="0" step="1" placeholder="Stock (facultatif)" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input className="wide" placeholder="URL de l'image (temporaire)" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><button>Publier le produit</button></form>{notice&&<p className="notice">{notice}</p>}</section>
 <section className="card"><h2>Mes produits</h2>{products.length===0?<p>Aucun produit.</p>:<div className="products">{products.map(p=><article key={p.id}>{p.image_url?<img src={p.image_url} alt={p.name}/>:<div className="ph">📦</div>}<div><h3>{p.name}</h3><p>{p.category}</p><b>{Number(p.price_amount??p.price_cfa).toLocaleString('fr-FR')} {p.currency_code==='XOF'||!p.currency_code?'CFA':p.currency_code}</b><small>{p.stock==null?'Stock non déclaré':`Stock: ${p.stock}`}</small><button className="danger" onClick={()=>removeProduct(p.id)}>Supprimer</button></div></article>)}</div>}</section>
 <section className="card"><h2>Clients</h2>{inquiries.length===0?<p>Aucune demande client.</p>:<div className="msgs">{inquiries.map(q=><article key={q.id}><b>Client</b><p>{q.message}</p>{q.reply?<div className="answer">Votre réponse: {q.reply}</div>:<button onClick={()=>reply(q)}>Répondre</button>}</article>)}</div>}</section>
 </main><style jsx>{`.wrap{max-width:1180px;margin:auto;padding:22px;color:#172033}.top{background:linear-gradient(135deg,#075dcc,#087ff0);color:#fff;border-radius:16px;padding:24px;display:flex;justify-content:space-between;gap:20px;align-items:center}.top h1{margin:4px 0}.actions{display:flex;gap:8px;flex-wrap:wrap}button{border:0;border-radius:9px;padding:10px 14px;background:#0875e8;color:#fff;font-weight:800;cursor:pointer}.top button{background:#fff;color:#075dcc}.top button:disabled{opacity:.5}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:16px 0}.stats div,.card{background:#fff;border:1px solid #e1e6ee;border-radius:14px;padding:18px}.stats b{display:block;font-size:24px;color:#075dcc}.stats span{font-size:12px;color:#667085}.card{margin-bottom:16px}.card h2{margin-top:0;color:#075dcc}.rule{background:#f7f9fc;padding:10px;border-radius:8px;color:#667085}.form{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.form input{padding:11px;border:1px solid #ccd5e2;border-radius:9px}.form .wide{grid-column:1/-1}.notice{background:#eef6ff;color:#075dcc;padding:10px;border-radius:8px}.products{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.products article{display:flex;border:1px solid #e1e6ee;border-radius:12px;overflow:hidden}.products img,.ph{width:120px;height:120px;object-fit:cover;display:grid;place-items:center;background:#f4f6f8;font-size:42px}.products article>div:last-child{padding:10px;flex:1}.products h3{margin:0}.products p,.products small{display:block;color:#667085;margin:5px 0}.danger{background:#d92d20;padding:6px 9px;margin-top:5px}.msgs{display:grid;gap:10px}.msgs article{border:1px solid #e1e6ee;border-radius:10px;padding:12px}.answer{background:#eef9f1;padding:9px;border-radius:8px}@media(max-width:700px){.wrap{padding:12px}.top{display:block}.actions{margin-top:12px}.stats{grid-template-columns:repeat(2,1fr)}.form,.products{grid-template-columns:1fr}.form .wide{grid-column:auto}}`}</style></AppShell>
}