'use client'

import {useEffect} from 'react'

const D={
 en:{'Déconnexion':'Sign out','Chargement...':'Loading...','Chargement TV…':'Loading TV…','Communication':'Communication','Marché':'Market','Boutiques':'Shops','Produits':'Products','Catégories':'Categories','Promotions':'Promotions','Nouveautés':'New arrivals','Top ventes':'Best sellers','Ma boutique':'My shop','Créer une boutique':'Create a shop','Gérer ma boutique':'Manage my shop','Découvrir les boutiques':'Discover shops','Boutiques actives':'Active shops','Aucune boutique active pour le moment.':'No active shop at the moment.','Entrer dans la boutique →':'Enter shop →','Vendez sur WakhReek':'Sell on WakhReek','Votre marché :':'Your market:','Rechercher des boutiques, produits...':'Search shops, products...','Aide':'Help','Inscription':'Sign up','Connexion':'Sign in','Nom complet':'Full name','Téléphone':'Phone','Mot de passe':'Password','Se connecter':'Sign in','Créer un compte':'Create account','Boutiques validées':'Verified shops','Contact client':'Customer contact','Espace vendeur':'Seller area','Ouvrir Market':'Open Market','Voir la boutique →':'View shop →','Tout voir':'View all','Boutiques WakhReek':'WakhReek shops','WakhReek TV est prêt':'WakhReek TV is ready','PUBLICITÉ':'ADVERTISEMENT','Publicité TV':'TV advertising','Voir ma boutique':'View my shop','Produits publiés':'Published products','Limite du plan':'Plan limit','Propriétaire':'Owner','Messages boutique reçus':'Shop messages received','Gérer mes publicités':'Manage my ads','Communication de la boutique':'Shop communication','Ouvrir les communications':'Open communications','Identité du propriétaire':'Owner identity','Nom du propriétaire':'Owner name','Fonction / métier':'Role / profession','Enregistrer mon identité':'Save my identity','Ajouter un produit':'Add a product','Nom du produit':'Product name','Catégorie':'Category','Prix':'Price','Stock (facultatif)':'Stock (optional)','Publier le produit':'Publish product','Mes produits':'My products','Supprimer':'Delete','Rechercher ou démarrer une discussion':'Search or start a conversation','Toutes':'All','Contacts':'Contacts','Groupes':'Groups','Message':'Message','Appel audio…':'Audio call…','Appel vidéo…':'Video call…','Connecté':'Connected','Accepter':'Accept','Refuser':'Reject','Envoyer':'Send'},
 es:{'Déconnexion':'Cerrar sesión','Chargement...':'Cargando...','Communication':'Comunicación','Marché':'Mercado','Boutiques':'Tiendas','Produits':'Productos','Catégories':'Categorías','Promotions':'Promociones','Nouveautés':'Novedades','Top ventes':'Más vendidos','Ma boutique':'Mi tienda','Créer une boutique':'Crear una tienda','Gérer ma boutique':'Gestionar mi tienda','Découvrir les boutiques':'Descubrir tiendas','Boutiques actives':'Tiendas activas','Entrer dans la boutique →':'Entrar en la tienda →','Votre marché :':'Tu mercado:','Aide':'Ayuda','Inscription':'Registro','Connexion':'Iniciar sesión','Nom complet':'Nombre completo','Téléphone':'Teléfono','Mot de passe':'Contraseña','Se connecter':'Iniciar sesión','Créer un compte':'Crear cuenta','Publicité TV':'Publicidad TV','Voir ma boutique':'Ver mi tienda','Produits publiés':'Productos publicados','Propriétaire':'Propietario','Ajouter un produit':'Añadir producto','Nom du produit':'Nombre del producto','Catégorie':'Categoría','Prix':'Precio','Mes produits':'Mis productos','Supprimer':'Eliminar','Toutes':'Todas','Contacts':'Contactos','Groupes':'Grupos','Accepter':'Aceptar','Refuser':'Rechazar','Envoyer':'Enviar'},
 pt:{'Déconnexion':'Sair','Chargement...':'Carregando...','Communication':'Comunicação','Marché':'Mercado','Boutiques':'Lojas','Produits':'Produtos','Catégories':'Categorias','Promotions':'Promoções','Nouveautés':'Novidades','Top ventes':'Mais vendidos','Ma boutique':'Minha loja','Créer une boutique':'Criar uma loja','Gérer ma boutique':'Gerir minha loja','Découvrir les boutiques':'Descobrir lojas','Boutiques actives':'Lojas ativas','Votre marché :':'Seu mercado:','Aide':'Ajuda','Inscription':'Cadastro','Connexion':'Entrar','Nom complet':'Nome completo','Téléphone':'Telefone','Mot de passe':'Senha','Se connecter':'Entrar','Créer un compte':'Criar conta','Publicité TV':'Publicidade TV','Voir ma boutique':'Ver minha loja','Produits publiés':'Produtos publicados','Propriétaire':'Proprietário','Ajouter un produit':'Adicionar produto','Nom du produit':'Nome do produto','Catégorie':'Categoria','Prix':'Preço','Mes produits':'Meus produtos','Supprimer':'Excluir','Toutes':'Todas','Contacts':'Contatos','Groupes':'Grupos','Accepter':'Aceitar','Refuser':'Recusar','Envoyer':'Enviar'},
 de:{'Déconnexion':'Abmelden','Chargement...':'Laden...','Communication':'Kommunikation','Marché':'Markt','Boutiques':'Shops','Produits':'Produkte','Catégories':'Kategorien','Promotions':'Angebote','Nouveautés':'Neuheiten','Top ventes':'Bestseller','Ma boutique':'Mein Shop','Créer une boutique':'Shop erstellen','Gérer ma boutique':'Shop verwalten','Découvrir les boutiques':'Shops entdecken','Boutiques actives':'Aktive Shops','Votre marché :':'Ihr Markt:','Aide':'Hilfe','Inscription':'Registrierung','Connexion':'Anmelden','Nom complet':'Vollständiger Name','Téléphone':'Telefon','Mot de passe':'Passwort','Se connecter':'Anmelden','Créer un compte':'Konto erstellen','Publicité TV':'TV-Werbung','Voir ma boutique':'Meinen Shop ansehen','Produits publiés':'Veröffentlichte Produkte','Propriétaire':'Inhaber','Ajouter un produit':'Produkt hinzufügen','Nom du produit':'Produktname','Catégorie':'Kategorie','Prix':'Preis','Mes produits':'Meine Produkte','Supprimer':'Löschen','Toutes':'Alle','Contacts':'Kontakte','Groupes':'Gruppen','Accepter':'Annehmen','Refuser':'Ablehnen','Envoyer':'Senden'},
 nl:{'Déconnexion':'Uitloggen','Chargement...':'Laden...','Communication':'Communicatie','Marché':'Markt','Boutiques':'Winkels','Produits':'Producten','Catégories':'Categorieën','Promotions':'Aanbiedingen','Nouveautés':'Nieuw','Top ventes':'Best verkocht','Ma boutique':'Mijn winkel','Créer une boutique':'Winkel maken','Gérer ma boutique':'Mijn winkel beheren','Découvrir les boutiques':'Winkels ontdekken','Boutiques actives':'Actieve winkels','Votre marché :':'Uw markt:','Aide':'Hulp','Inscription':'Registreren','Connexion':'Inloggen','Nom complet':'Volledige naam','Téléphone':'Telefoon','Mot de passe':'Wachtwoord','Se connecter':'Inloggen','Créer un compte':'Account maken','Publicité TV':'TV-reclame','Voir ma boutique':'Mijn winkel bekijken','Produits publiés':'Gepubliceerde producten','Propriétaire':'Eigenaar','Ajouter un produit':'Product toevoegen','Nom du produit':'Productnaam','Catégorie':'Categorie','Prix':'Prijs','Mes produits':'Mijn producten','Supprimer':'Verwijderen','Toutes':'Alle','Contacts':'Contacten','Groupes':'Groepen','Accepter':'Accepteren','Refuser':'Weigeren','Envoyer':'Verzenden'},
 ar:{'Déconnexion':'تسجيل الخروج','Chargement...':'جارٍ التحميل...','Chargement TV…':'جارٍ تحميل التلفاز…','Communication':'التواصل','Marché':'السوق','Boutiques':'المتاجر','Produits':'المنتجات','Catégories':'الفئات','Promotions':'العروض','Nouveautés':'الجديد','Top ventes':'الأكثر مبيعاً','Ma boutique':'متجري','Créer une boutique':'إنشاء متجر','Gérer ma boutique':'إدارة متجري','Découvrir les boutiques':'اكتشف المتاجر','Boutiques actives':'المتاجر النشطة','Aucune boutique active pour le moment.':'لا توجد متاجر نشطة حالياً.','Entrer dans la boutique →':'دخول المتجر ←','Vendez sur WakhReek':'بِع على WakhReek','Votre marché :':'سوقك:','Rechercher des boutiques, produits...':'ابحث عن متاجر أو منتجات...','Aide':'مساعدة','Inscription':'التسجيل','Connexion':'تسجيل الدخول','Nom complet':'الاسم الكامل','Téléphone':'الهاتف','Mot de passe':'كلمة المرور','Se connecter':'تسجيل الدخول','Créer un compte':'إنشاء حساب','Boutiques validées':'متاجر موثقة','Contact client':'تواصل الزبون','Espace vendeur':'فضاء البائع','Ouvrir Market':'فتح السوق','Voir la boutique →':'عرض المتجر ←','Tout voir':'عرض الكل','Boutiques WakhReek':'متاجر WakhReek','WakhReek TV est prêt':'WakhReek TV جاهز','PUBLICITÉ':'إعلان','Publicité TV':'إعلان تلفزيوني','Voir ma boutique':'عرض متجري','Produits publiés':'المنتجات المنشورة','Limite du plan':'حد الخطة','Propriétaire':'المالك','Messages boutique reçus':'رسائل المتجر المستلمة','Gérer mes publicités':'إدارة إعلاناتي','Communication de la boutique':'تواصل المتجر','Ouvrir les communications':'فتح التواصل','Identité du propriétaire':'هوية المالك','Nom du propriétaire':'اسم المالك','Fonction / métier':'الوظيفة / المهنة','Enregistrer mon identité':'حفظ هويتي','Ajouter un produit':'إضافة منتج','Nom du produit':'اسم المنتج','Catégorie':'الفئة','Prix':'السعر','Stock (facultatif)':'المخزون (اختياري)','Publier le produit':'نشر المنتج','Mes produits':'منتجاتي','Supprimer':'حذف','Rechercher ou démarrer une discussion':'البحث أو بدء محادثة','Toutes':'الكل','Contacts':'جهات الاتصال','Groupes':'المجموعات','Message':'رسالة','Appel audio…':'مكالمة صوتية…','Appel vidéo…':'مكالمة فيديو…','Connecté':'متصل','Accepter':'قبول','Refuser':'رفض','Envoyer':'إرسال'}
}

const originals=new WeakMap()
function translate(root,lang){
 const dict=D[lang]||{}
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT)
 let n
 while((n=walker.nextNode())){
  const p=n.parentElement;if(!p||['SCRIPT','STYLE','OPTION','TEXTAREA'].includes(p.tagName)||p.closest('.wr-language'))continue
  if(!originals.has(n))originals.set(n,n.nodeValue)
  const original=originals.get(n),trim=original.trim(),value=dict[trim]
  if(value)n.nodeValue=original.replace(trim,value);else if(lang==='fr')n.nodeValue=original
 }
 root.querySelectorAll?.('input[placeholder],textarea[placeholder]').forEach(el=>{
  if(!el.dataset.wrOriginalPlaceholder)el.dataset.wrOriginalPlaceholder=el.placeholder
  const o=el.dataset.wrOriginalPlaceholder;el.placeholder=lang==='fr'?o:(dict[o]||o)
 })
}

export default function AutoTranslator(){
 useEffect(()=>{
  let lang=localStorage.getItem('wakhreek_language')||'fr',queued=false
  const run=()=>{queued=false;translate(document.body,lang)}
  const queue=()=>{if(!queued){queued=true;requestAnimationFrame(run)}}
  const change=e=>{lang=e.detail?.language||'fr';queue()}
  const observer=new MutationObserver(queue);observer.observe(document.body,{childList:true,subtree:true,characterData:true})
  window.addEventListener('wakhreek-language-change',change);queue()
  return()=>{observer.disconnect();window.removeEventListener('wakhreek-language-change',change)}
 },[])
 return null
}
