'use client'
import {useMemo,useState} from 'react'
export default function BoutiqueOwnerAssistant({shop,products=[],messageCount=0,subscription,categories=[]}){
 const[open,setOpen]=useState(false),[answer,setAnswer]=useState('')
 const info=useMemo(()=>{const limit=shop?.product_count_limit,remaining=limit==null?null:Math.max(0,limit-products.length),low=products.filter(p=>p.stock!=null&&Number(p.stock)<=3),noStock=products.filter(p=>p.stock==null);return{limit,remaining,low,noStock}},[shop,products])
 function advise(type){
  if(type==='products'){if(!shop?.is_live)return setAnswer('متجرك غير نشط بعد. يمكنك تجهيز المعلومات، لكن نشر المنتجات يتطلب تفعيل المتجر.');if(info.remaining===0)return setAnswer('وصلت إلى الحد الأقصى لمنتجات خطتك. لا أغيّر الخطة أو الرسوم تلقائيًا؛ يمكنك مراجعة خطة المتجر.');setAnswer(info.remaining==null?`لديك ${products.length} منتجًا منشورًا وخطتك غير محدودة.`:`لديك ${products.length} منتجًا، ويمكنك إضافة ${info.remaining} ضمن خطتك الحالية.`)}
  if(type==='stock')setAnswer(info.low.length?`تنبيه مخزون: ${info.low.length} منتج/منتجات مخزونها 3 أو أقل: ${info.low.slice(0,4).map(p=>p.name).join('، ')}.`:info.noStock.length?`لا يوجد مخزون منخفض مسجل، لكن ${info.noStock.length} منتج/منتجات بدون كمية مخزون معلنة.`:'المخزون المسجل لا يحتوي حاليًا على منتج بكمية 3 أو أقل.')
  if(type==='messages')setAnswer(messageCount?`لديك ${messageCount} رسالة متجر. افتح قسم اتصالات البوتيك للرد على الزبناء.`:'لا توجد رسائل متجر مسجلة حاليًا.')
  if(type==='payment')setAnswer(!subscription?'لا يوجد اشتراك مرتبط ظاهر حاليًا.':subscription.status==='approved'?'اشتراك المتجر معتمد.':subscription.status==='rejected'?'الاشتراك مرفوض حاليًا؛ راجع حالة الدفع مع إدارة WakhReek.':'الاشتراك ما زال في انتظار المراجعة. المساعد لا يعتمد المدفوعات بنفسه.')
 }
 return <><button onClick={()=>setOpen(x=>!x)} style={fab}>🤖 مساعد التاجر</button>{open&&<aside style={panel} dir="auto"><div style={head}><b>🤖 WakhReek Seller AI</b><button onClick={()=>setOpen(false)} style={close}>×</button></div><p style={muted}>مساعد خاص بمتجرك <b>{shop?.name}</b>. يقرأ حالة المتجر والمنتجات فقط ليعطيك توجيهًا، ولا يغيّر السعر أو المخزون أو الدفع دون قرارك.</p><div style={grid}><button onClick={()=>advise('products')}>📦 المنتجات والخطة</button><button onClick={()=>advise('stock')}>📊 المخزون</button><button onClick={()=>advise('messages')}>💬 رسائل الزبناء</button><button onClick={()=>advise('payment')}>💳 الاشتراك والدفع</button></div>{answer&&<div style={reply}>{answer}</div>}<small style={muted}>البيع، الثمن، الصور والمخزون تبقى تحت مسؤولية وقرار صاحب المتجر.</small></aside>}</>
}
const fab={position:'fixed',right:20,bottom:24,zIndex:9100,border:0,borderRadius:28,padding:'13px 18px',background:'#075dcc',color:'#fff',fontWeight:800,cursor:'pointer',boxShadow:'0 8px 30px #0004'}
const panel={position:'fixed',right:20,bottom:82,zIndex:9100,width:'min(410px,calc(100vw - 28px))',background:'#fff',border:'1px solid #dce4ef',borderRadius:18,padding:16,boxShadow:'0 18px 55px #0003',color:'#172033'}
const head={display:'flex',justifyContent:'space-between',alignItems:'center'},close={border:0,background:'transparent',fontSize:25,cursor:'pointer'},grid={display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,margin:'12px 0'},reply={background:'#eef6ff',borderRadius:12,padding:12,lineHeight:1.6,margin:'10px 0'},muted={color:'#667085',lineHeight:1.5}
