'use client'
import {useEffect,useMemo,useState} from 'react'
import {usePathname} from 'next/navigation'
import {supabase} from '../lib/supabase'
import {useI18n} from './I18nProvider'

const COPY={
 fr:{fab:'🤖 Assistant vendeur',title:'🤖 WakhReek Seller AI',intro:n=>`Assistant de votre boutique ${n}. Il lit l’état de la boutique pour vous guider, sans modifier prix, stock ou paiement sans votre décision.`,products:'📦 Produits et plan',stock:'📊 Stock',messages:'💬 Messages clients',payment:'💳 Abonnement et paiement',inactive:'Votre boutique n’est pas encore active. Vous pouvez préparer ses informations, mais la publication dépend de son activation.',limit:'Vous avez atteint la limite de produits de votre plan. L’assistant ne change ni le plan ni les frais automatiquement.',unlimited:n=>`Vous avez ${n} produit(s) publié(s) et votre plan est illimité.`,remaining:(n,r)=>`Vous avez ${n} produit(s) et pouvez encore en ajouter ${r} avec votre plan actuel.`,low:(n,names)=>`Alerte stock : ${n} produit(s) ont un stock de 3 ou moins : ${names}.`,nostock:n=>`Aucun stock faible enregistré, mais ${n} produit(s) n’ont pas de quantité déclarée.`,stockok:'Aucun produit enregistré n’a actuellement un stock de 3 ou moins.',msg:n=>`Vous avez ${n} message(s) boutique. Ouvrez les communications de la boutique pour répondre aux clients.`,nomsg:'Aucun message boutique enregistré actuellement.',nosub:'Aucun abonnement associé visible actuellement.',approved:'L’abonnement de la boutique est approuvé.',rejected:'L’abonnement est refusé actuellement ; vérifiez son état avec l’administration WakhReek.',pending:'L’abonnement est encore en attente de vérification. L’assistant n’approuve pas les paiements lui-même.',note:'La vente, les prix, les images et le stock restent sous la responsabilité et la décision du vendeur.'},
 ar:{fab:'🤖 مساعد التاجر',title:'🤖 مساعد بائع WakhReek',intro:n=>`مساعد خاص بمتجرك ${n}. يقرأ حالة متجرك ليعطيك توجيهًا، ولا يغيّر السعر أو المخزون أو الدفع دون قرارك.`,products:'📦 المنتجات والخطة',stock:'📊 المخزون',messages:'💬 رسائل الزبناء',payment:'💳 الاشتراك والدفع',inactive:'متجرك غير نشط بعد. يمكنك تجهيز معلوماته، لكن نشر المنتجات يتطلب تفعيل المتجر.',limit:'وصلت إلى الحد الأقصى لمنتجات خطتك. المساعد لا يغيّر خطتك أو الرسوم تلقائيًا.',unlimited:n=>`لديك ${n} منتجًا منشورًا وخطتك غير محدودة.`,remaining:(n,r)=>`لديك ${n} منتجًا، ويمكنك إضافة ${r} ضمن خطتك الحالية.`,low:(n,names)=>`تنبيه مخزون: ${n} منتج/منتجات مخزونها 3 أو أقل: ${names}.`,nostock:n=>`لا يوجد مخزون منخفض مسجل، لكن ${n} منتج/منتجات بدون كمية مخزون معلنة.`,stockok:'المخزون المسجل لا يحتوي حاليًا على منتج بكمية 3 أو أقل.',msg:n=>`لديك ${n} رسالة متجر. افتح اتصالات البوتيك للرد على الزبناء.`,nomsg:'لا توجد رسائل متجر مسجلة حاليًا.',nosub:'لا يوجد اشتراك مرتبط ظاهر حاليًا.',approved:'اشتراك المتجر معتمد.',rejected:'الاشتراك مرفوض حاليًا؛ راجع الحالة مع إدارة WakhReek.',pending:'الاشتراك ما زال في انتظار المراجعة. المساعد لا يعتمد المدفوعات بنفسه.',note:'البيع والثمن والصور والمخزون تبقى تحت مسؤولية وقرار صاحب المتجر.'},
 en:{fab:'🤖 Seller assistant',title:'🤖 WakhReek Seller AI',intro:n=>`Assistant for your shop ${n}. It reads your shop status to guide you and never changes price, stock or payment without your decision.`,products:'📦 Products and plan',stock:'📊 Stock',messages:'💬 Customer messages',payment:'💳 Subscription and payment',inactive:'Your shop is not active yet. You can prepare its information, but publishing products requires activation.',limit:'You have reached your plan product limit. The assistant does not change your plan or fees automatically.',unlimited:n=>`You have ${n} published product(s) and an unlimited plan.`,remaining:(n,r)=>`You have ${n} product(s) and can add ${r} more under your current plan.`,low:(n,names)=>`Stock alert: ${n} product(s) have stock of 3 or less: ${names}.`,nostock:n=>`No low stock is recorded, but ${n} product(s) have no declared stock quantity.`,stockok:'No recorded product currently has stock of 3 or less.',msg:n=>`You have ${n} shop message(s). Open boutique communications to reply to customers.`,nomsg:'There are currently no recorded shop messages.',nosub:'No associated subscription is currently visible.',approved:'The shop subscription is approved.',rejected:'The subscription is currently rejected; check its status with WakhReek administration.',pending:'The subscription is still awaiting review. The assistant does not approve payments itself.',note:'Sales, prices, images and stock remain under the seller’s responsibility and decision.'}
}
export default function BoutiqueOwnerAssistant(){
 const pathname=usePathname(),{language}=useI18n(),c=COPY[language]||COPY.fr,[shop,setShop]=useState(null),[products,setProducts]=useState([]),[messageCount,setMessageCount]=useState(0),[subscription,setSubscription]=useState(null),[open,setOpen]=useState(false),[answer,setAnswer]=useState('')
 const active=pathname==='/market/my-boutique'
 useEffect(()=>{setAnswer('')},[language])
 useEffect(()=>{if(!active)return;(async()=>{const{data:a}=await supabase.auth.getUser(),u=a?.user;if(!u)return;const{data:b}=await supabase.from('boutiques').select('id,name,is_live,product_count_limit').eq('user_id',u.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!b)return;setShop(b);const[{data:p},{count:m},{data:s}]=await Promise.all([supabase.from('products').select('id,name,stock').eq('boutique_id',b.id),supabase.from('market_boutique_messages').select('id',{count:'exact',head:true}).eq('boutique_id',b.id).eq('recipient_id',u.id),supabase.from('subscriptions').select('status').eq('boutique_id',b.id).order('created_at',{ascending:false}).limit(1).maybeSingle()]);setProducts(p||[]);setMessageCount(m||0);setSubscription(s||null)})()},[active])
 const info=useMemo(()=>{const limit=shop?.product_count_limit,remaining=limit==null?null:Math.max(0,limit-products.length),low=products.filter(p=>p.stock!=null&&Number(p.stock)<=3),noStock=products.filter(p=>p.stock==null);return{remaining,low,noStock}},[shop,products])
 function advise(type){if(type==='products'){if(!shop?.is_live)return setAnswer(c.inactive);if(info.remaining===0)return setAnswer(c.limit);return setAnswer(info.remaining==null?c.unlimited(products.length):c.remaining(products.length,info.remaining))}if(type==='stock')return setAnswer(info.low.length?c.low(info.low.length,info.low.slice(0,4).map(p=>p.name).join('، ')):info.noStock.length?c.nostock(info.noStock.length):c.stockok);if(type==='messages')return setAnswer(messageCount?c.msg(messageCount):c.nomsg);if(type==='payment')return setAnswer(!subscription?c.nosub:subscription.status==='approved'?c.approved:subscription.status==='rejected'?c.rejected:c.pending)}
 if(!active||!shop)return null
 return <><button onClick={()=>setOpen(x=>!x)} style={fab}>{c.fab}</button>{open&&<aside style={panel} dir={language==='ar'?'rtl':'ltr'}><div style={head}><b>{c.title}</b><button onClick={()=>setOpen(false)} style={close}>×</button></div><p style={muted}>{c.intro(shop.name)}</p><div style={grid}><button onClick={()=>advise('products')}>{c.products}</button><button onClick={()=>advise('stock')}>{c.stock}</button><button onClick={()=>advise('messages')}>{c.messages}</button><button onClick={()=>advise('payment')}>{c.payment}</button></div>{answer&&<div style={reply}>{answer}</div>}<small style={muted}>{c.note}</small></aside>}</>}
const fab={position:'fixed',right:20,bottom:24,zIndex:9100,border:0,borderRadius:28,padding:'13px 18px',background:'#075dcc',color:'#fff',fontWeight:800,cursor:'pointer',boxShadow:'0 8px 30px #0004'},panel={position:'fixed',right:20,bottom:82,zIndex:9100,width:'min(410px,calc(100vw - 28px))',background:'#fff',border:'1px solid #dce4ef',borderRadius:18,padding:16,boxShadow:'0 18px 55px #0003',color:'#172033'},head={display:'flex',justifyContent:'space-between',alignItems:'center'},close={border:0,background:'transparent',fontSize:25,cursor:'pointer'},grid={display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,margin:'12px 0'},reply={background:'#eef6ff',borderRadius:12,padding:12,lineHeight:1.6,margin:'10px 0'},muted={color:'#667085',lineHeight:1.5}
