'use client'
import {useEffect,useMemo,useState} from 'react'
import {usePathname} from 'next/navigation'
import {supabase} from '../lib/supabase'
export default function BoutiqueOwnerAssistant(){
 const pathname=usePathname(),[shop,setShop]=useState(null),[products,setProducts]=useState([]),[messageCount,setMessageCount]=useState(0),[subscription,setSubscription]=useState(null),[open,setOpen]=useState(false),[answer,setAnswer]=useState('')
 const active=pathname==='/market/my-boutique'
 useEffect(()=>{if(!active)return;(async()=>{const{data:a}=await supabase.auth.getUser(),u=a?.user;if(!u)return;const{data:b}=await supabase.from('boutiques').select('id,name,is_live,product_count_limit').eq('user_id',u.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!b)return;setShop(b);const[{data:p},{count:m},{data:s}]=await Promise.all([supabase.from('products').select('id,name,stock').eq('boutique_id',b.id),supabase.from('market_boutique_messages').select('id',{count:'exact',head:true}).eq('boutique_id',b.id).eq('recipient_id',u.id),supabase.from('subscriptions').select('status').eq('boutique_id',b.id).order('created_at',{ascending:false}).limit(1).maybeSingle()]);setProducts(p||[]);setMessageCount(m||0);setSubscription(s||null)})()},[active])
 const info=useMemo(()=>{const limit=shop?.product_count_limit,remaining=limit==null?null:Math.max(0,limit-products.length),low=products.filter(p=>p.stock!=null&&Number(p.stock)<=3),noStock=products.filter(p=>p.stock==null);return{remaining,low,noStock}},[shop,products])
 function advise(type){if(type==='products'){if(!shop?.is_live)return setAnswer('متجرك غير نشط بعد. يمكنك تجهيز معلوماته، لكن نشر المنتجات يتطلب تفعيل المتجر.');if(info.remaining===0)return setAnswer('وصلت إلى الحد الأقصى لمنتجات خطتك. المساعد لا يغيّر خطتك أو الرسوم تلقائيًا.');return setAnswer(info.remaining==null?`لديك ${products.length} منتجًا منشورًا وخطتك غير محدودة.`:`لديك ${products.length} منتجًا، ويمكنك إضافة ${info.remaining} ضمن خطتك الحالية.`)}if(type==='stock')return setAnswer(info.low.length?`تنبيه مخزون: ${info.low.length} منتج/منتجات مخزونها 3 أو أقل: ${info.low.slice(0,4).map(p=>p.name).join('، ')}.`:info.noStock.length?`لا يوجد مخزون منخفض مسجل، لكن ${info.noStock.length} منتج/منتجات بدون كمية مخزون معلنة.`:'المخزون المسجل لا يحتوي حاليًا على منتج بكمية 3 أو أقل.');if(type==='messages')return setAnswer(messageCount?`لديك ${messageCount} رسالة متجر. افتح اتصالات البوتيك للرد على الزبناء.`:'لا توجد رسائل متجر مسجلة حاليًا.');if(type==='payment')return setAnswer(!subscription?'لا يوجد اشتراك مرتبط ظاهر حاليًا.':subscription.status==='approved'?'اشتراك المتجر معتمد.':subscription.status==='rejected'?'الاشتراك مرفوض حاليًا؛ راجع الحالة مع إدارة WakhReek.':'الاشتراك ما زال في انتظار المراجعة. المساعد لا يعتمد المدفوعات بنفسه.')}
 if(!active||!shop)return null
 return <><button onClick={()=>setOpen(x=>!x)} style={fab}>🤖 مساعد التاجر</button>{open&&<aside style={panel} dir="auto"><div style={head}><b>🤖 WakhReek Seller AI</b><button onClick={()=>setOpen(false)} style={close}>×</button></div><p style={muted}>مساعد خاص بمتجرك <b>{shop.name}</b>. يقرأ حالة متجرك ليعطيك توجيهًا، ولا يغيّر السعر أو المخزون أو الدفع دون قرارك.</p><div style={grid}><button onClick={()=>advise('products')}>📦 المنتجات والخطة</button><button onClick={()=>advise('stock')}>📊 المخزون</button><button onClick={()=>advise('messages')}>💬 رسائل الزبناء</button><button onClick={()=>advise('payment')}>💳 الاشتراك والدفع</button></div>{answer&&<div style={reply}>{answer}</div>}<small style={muted}>البيع والثمن والصور والمخزون تبقى تحت مسؤولية وقرار صاحب المتجر.</small></aside>}</>}
const fab={position:'fixed',right:20,bottom:24,zIndex:9100,border:0,borderRadius:28,padding:'13px 18px',background:'#075dcc',color:'#fff',fontWeight:800,cursor:'pointer',boxShadow:'0 8px 30px #0004'},panel={position:'fixed',right:20,bottom:82,zIndex:9100,width:'min(410px,calc(100vw - 28px))',background:'#fff',border:'1px solid #dce4ef',borderRadius:18,padding:16,boxShadow:'0 18px 55px #0003',color:'#172033'},head={display:'flex',justifyContent:'space-between',alignItems:'center'},close={border:0,background:'transparent',fontSize:25,cursor:'pointer'},grid={display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,margin:'12px 0'},reply={background:'#eef6ff',borderRadius:12,padding:12,lineHeight:1.6,margin:'10px 0'},muted={color:'#667085',lineHeight:1.5}
