'use client'
import {useMemo,useState} from 'react'
import {useI18n} from './I18nProvider'

function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
const copy={
 ar:{title:'🤖 WakhReek Market AI',intro:'أساعدك في العثور على المنتجات والمتاجر الموجودة فعليًا داخل WakhReek Market.',product:'🛍 منتج',shop:'🏪 متجر',near:'📍 قريب مني',productHelp:'اكتب اسم المنتج الذي تبحث عنه، وسأبحث داخل متاجر WakhReek النشطة.',shopHelp:'اكتب اسم المتجر الذي تبحث عنه.',nearHelp:'اختر بلدك ومدينتك من أعلى Market، ثم اكتب ما تبحث عنه وسأطابقه مع المتاجر المتاحة.',placeholder:'مثال: صابون مغربي، ملابس، متجر...',search:'بحث',found:(n,names)=>`وجدت ${n} متجرًا مرتبطًا بطلبك: ${names}. سأعرض لك النتائج الموجودة فعليًا في WakhReek.`,none:'لم أجد نتيجة مطابقة في متاجر WakhReek النشطة حاليًا. جرّب اسم المنتج أو المتجر أو فئة أقصر. لن أقترح عليك منتجًا غير موجود في السوق.',note:'المساعد يعتمد على بيانات WakhReek Market الحالية ولا يوافق على المتاجر أو المدفوعات.'},
 fr:{title:'🤖 WakhReek Market AI',intro:'Je vous aide à trouver les produits et boutiques réellement disponibles dans WakhReek Market.',product:'🛍 Produit',shop:'🏪 Boutique',near:'📍 Près de moi',productHelp:'Saisissez le nom du produit recherché et je chercherai dans les boutiques WakhReek actives.',shopHelp:'Saisissez le nom de la boutique recherchée.',nearHelp:'Choisissez votre pays et votre ville en haut du Market, puis indiquez ce que vous cherchez.',placeholder:'Ex. savon marocain, vêtements, boutique...',search:'Rechercher',found:(n,names)=>`J’ai trouvé ${n} boutique(s) liée(s) à votre recherche : ${names}. Je vous affiche uniquement les résultats réellement présents dans WakhReek.`,none:'Aucun résultat correspondant dans les boutiques WakhReek actives. Essayez un nom de produit, de boutique ou une catégorie plus courte.',note:'L’assistant utilise les données actuelles de WakhReek Market et ne valide ni boutiques ni paiements.'},
 en:{title:'🤖 WakhReek Market AI',intro:'I help you find products and shops that are actually available in WakhReek Market.',product:'🛍 Product',shop:'🏪 Shop',near:'📍 Near me',productHelp:'Enter the product name and I will search active WakhReek shops.',shopHelp:'Enter the shop name you are looking for.',nearHelp:'Choose your country and city at the top of Market, then enter what you are looking for.',placeholder:'Example: Moroccan soap, clothes, shop...',search:'Search',found:(n,names)=>`I found ${n} shop(s) related to your search: ${names}. I will show only results actually available in WakhReek.`,none:'No matching result was found in active WakhReek shops. Try a product name, shop name, or shorter category.',note:'The assistant uses current WakhReek Market data and does not approve shops or payments.'},
 pt:{title:'🤖 WakhReek Market AI',intro:'Ajudo você a encontrar produtos e lojas realmente disponíveis no WakhReek Market.',product:'🛍 Produto',shop:'🏪 Loja',near:'📍 Perto de mim',productHelp:'Digite o nome do produto que procura e pesquisarei nas lojas WakhReek ativas.',shopHelp:'Digite o nome da loja que procura.',nearHelp:'Escolha seu país e sua cidade no topo do Market e depois diga o que procura.',placeholder:'Ex.: sabão marroquino, roupas, loja...',search:'Pesquisar',found:(n,names)=>`Encontrei ${n} loja(s) relacionada(s) à sua pesquisa: ${names}. Mostrarei apenas resultados realmente disponíveis no WakhReek.`,none:'Não encontrei resultados correspondentes nas lojas WakhReek ativas. Tente o nome de um produto, de uma loja ou uma categoria mais curta.',note:'O assistente usa os dados atuais do WakhReek Market e não aprova lojas nem pagamentos.'}
}
export default function MarketAssistant({shops=[],products=[],countries=[],cities=[],onSearch}){
 const{language}=useI18n();const l=copy[language]||copy.en
 const[open,setOpen]=useState(false),[text,setText]=useState(''),[answer,setAnswer]=useState('')
 const index=useMemo(()=>({shops,products,countries,cities}),[shops,products,countries,cities])
 function ask(e){e.preventDefault();const q=norm(text);if(!q)return
  const ps=index.products.filter(p=>norm(p.name).includes(q)||norm(p.category).includes(q)).slice(0,5)
  const ss=index.shops.filter(s=>norm(s.name).includes(q)).slice(0,5)
  const productShops=[...new Set(ps.map(p=>p.boutique_id))].map(id=>index.shops.find(s=>s.id===id)).filter(Boolean)
  const found=[...ss,...productShops].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i)
  if(found.length){setAnswer(l.found(found.length,found.map(x=>x.name).join(language==='ar'?'، ':', ')));onSearch?.(text)}
  else{setAnswer(l.none);onSearch?.(text)}
 }
 return <><button onClick={()=>setOpen(x=>!x)} style={fab}>🤖 <span>WakhReek AI</span></button>{open&&<section style={panel} dir={language==='ar'?'rtl':'ltr'}><header style={head}><b>{l.title}</b><button onClick={()=>setOpen(false)} style={close}>×</button></header><p style={intro}>{l.intro}</p><div style={quick}><button onClick={()=>{setText('');setAnswer(l.productHelp)}}>{l.product}</button><button onClick={()=>{setText('');setAnswer(l.shopHelp)}}>{l.shop}</button><button onClick={()=>setAnswer(l.nearHelp)}>{l.near}</button></div><form onSubmit={ask} style={form}><input value={text} onChange={e=>setText(e.target.value)} placeholder={l.placeholder} autoFocus/><button>{l.search}</button></form>{answer&&<div style={reply}>{answer}</div>}<small style={{opacity:.65}}>{l.note}</small></section>}</>
}
const fab={position:'fixed',right:20,bottom:24,zIndex:9000,border:0,borderRadius:28,padding:'13px 18px',background:'#111827',color:'#fff',fontWeight:800,cursor:'pointer',boxShadow:'0 8px 30px #0004'}
const panel={position:'fixed',right:20,bottom:82,zIndex:9000,width:'min(390px,calc(100vw - 28px))',background:'#fff',border:'1px solid #dde4ee',borderRadius:18,padding:16,boxShadow:'0 18px 55px #0003',color:'#172033'}
const head={display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:17},close={border:0,background:'transparent',fontSize:25,cursor:'pointer'},intro={fontSize:13,lineHeight:1.5,color:'#596579'},quick={display:'flex',gap:7,flexWrap:'wrap',margin:'10px 0'},form={display:'flex',gap:7,margin:'12px 0'},reply={background:'#eef6ff',padding:12,borderRadius:12,lineHeight:1.6,marginBottom:10}
