import {extraMessages} from './i18n-extra'
export const LANGUAGES=[
 {code:'fr',flag:'🇫🇷',name:'Français',dir:'ltr'},{code:'ar',flag:'🇲🇦',name:'العربية',dir:'rtl'},{code:'en',flag:'🇬🇧',name:'English',dir:'ltr'},{code:'es',flag:'🇪🇸',name:'Español',dir:'ltr'},{code:'pt',flag:'🇵🇹',name:'Português',dir:'ltr'},{code:'de',flag:'🇩🇪',name:'Deutsch',dir:'ltr'},{code:'nl',flag:'🇳🇱',name:'Nederlands',dir:'ltr'}
]
export const DEFAULT_LANGUAGE='fr'
export const LANGUAGE_CODES=new Set(LANGUAGES.map(x=>x.code))
const common={tv:'WakhReek TV'}
const admin={
 fr:{adminProtected:'Accès Admin protégé',adminOnly:'Cette page est réservée au compte administrateur WakhReek.',adminSubtitle:'Gestion protégée des boutiques, paiements et WakhReek TV',notSubmitted:'Pas encore soumis',toReview:'À vérifier',approvedPayments:'Paiements approuvés',rejectedPayments:'Paiements refusés',pendingTvAds:'Publicités TV en attente',paymentsToReview:'💳 Paiements à vérifier',paymentsWaiting:'⏳ Paiements pas encore soumis',approvedHistory:'✅ Paiements approuvés',rejectedHistory:'❌ Paiements refusés',noItem:'Aucun élément.',noPayment:'Aucun paiement',notConfigured:'Non configuré',notSubmittedYet:'Pas encore soumise',sellerReferenceWaiting:'⏳ Référence vendeur attendue',paymentMethodNotConfigured:'Moyen de paiement non configuré',approvePayment:'Approuver le paiement',rejectPayment:'Refuser le paiement',tvDivision:'📺 Division Publicité — WakhReek TV',noTvAd:'Aucune publicité TV.',approveActivate:'Approuver / Activer',pause:'Pause',finish:'Terminer',plan:'Plan',state:'État',adminActions:'Actions Admin',freeActivationNote:'L’activation gratuite Admin reste indépendante du circuit de paiement.',activateFree:'Activer gratuit',deactivate:'Désactiver'},
 ar:{adminProtected:'دخول الإدارة محمي',adminOnly:'هذه الصفحة مخصصة لحساب إدارة WakhReek.',adminSubtitle:'إدارة محمية للمتاجر والمدفوعات وWakhReek TV',notSubmitted:'لم يُرسل بعد',toReview:'للمراجعة',approvedPayments:'مدفوعات مقبولة',rejectedPayments:'مدفوعات مرفوضة',pendingTvAds:'إعلانات TV قيد الانتظار',paymentsToReview:'💳 مدفوعات للمراجعة',paymentsWaiting:'⏳ مدفوعات لم تُرسل بعد',approvedHistory:'✅ مدفوعات مقبولة',rejectedHistory:'❌ مدفوعات مرفوضة',noItem:'لا توجد عناصر.',noPayment:'لا يوجد دفع',notConfigured:'غير مهيأ',notSubmittedYet:'لم يُرسل بعد',sellerReferenceWaiting:'⏳ في انتظار مرجع البائع',paymentMethodNotConfigured:'وسيلة الدفع غير مهيأة',approvePayment:'قبول الدفع',rejectPayment:'رفض الدفع',tvDivision:'📺 قسم الإعلانات — WakhReek TV',noTvAd:'لا توجد إعلانات TV.',approveActivate:'قبول / تفعيل',pause:'إيقاف مؤقت',finish:'إنهاء',plan:'الخطة',state:'الحالة',adminActions:'إجراءات الإدارة',freeActivationNote:'التفعيل المجاني من الإدارة مستقل عن مسار الدفع.',activateFree:'تفعيل مجاني',deactivate:'تعطيل'},
 en:{adminProtected:'Protected Admin access',adminOnly:'This page is reserved for the WakhReek administrator account.',adminSubtitle:'Protected management of shops, payments and WakhReek TV',notSubmitted:'Not submitted yet',toReview:'To review',approvedPayments:'Approved payments',rejectedPayments:'Rejected payments',pendingTvAds:'Pending TV ads',paymentsToReview:'💳 Payments to review',paymentsWaiting:'⏳ Payments not submitted yet',approvedHistory:'✅ Approved payments',rejectedHistory:'❌ Rejected payments',noItem:'No items.',noPayment:'No payment',notConfigured:'Not configured',notSubmittedYet:'Not submitted yet',sellerReferenceWaiting:'⏳ Waiting for seller reference',paymentMethodNotConfigured:'Payment method not configured',approvePayment:'Approve payment',rejectPayment:'Reject payment',tvDivision:'📺 Advertising Division — WakhReek TV',noTvAd:'No TV ads.',approveActivate:'Approve / Activate',pause:'Pause',finish:'Finish',plan:'Plan',state:'State',adminActions:'Admin actions',freeActivationNote:'Free Admin activation remains independent from the payment flow.',activateFree:'Activate free',deactivate:'Deactivate'},
 es:{adminProtected:'Acceso Admin protegido',adminOnly:'Esta página está reservada para la cuenta administradora de WakhReek.',adminSubtitle:'Gestión protegida de tiendas, pagos y WakhReek TV',notSubmitted:'Aún no enviado',toReview:'Por revisar',approvedPayments:'Pagos aprobados',rejectedPayments:'Pagos rechazados',pendingTvAds:'Anuncios TV pendientes',paymentsToReview:'💳 Pagos por revisar',paymentsWaiting:'⏳ Pagos aún no enviados',approvedHistory:'✅ Pagos aprobados',rejectedHistory:'❌ Pagos rechazados',noItem:'Ningún elemento.',noPayment:'Sin pago',notConfigured:'No configurado',notSubmittedYet:'Aún no enviada',sellerReferenceWaiting:'⏳ Esperando referencia del vendedor',paymentMethodNotConfigured:'Método de pago no configurado',approvePayment:'Aprobar pago',rejectPayment:'Rechazar pago',tvDivision:'📺 División Publicidad — WakhReek TV',noTvAd:'Sin anuncios TV.',approveActivate:'Aprobar / Activar',pause:'Pausa',finish:'Finalizar',plan:'Plan',state:'Estado',adminActions:'Acciones Admin',freeActivationNote:'La activación gratuita Admin es independiente del pago.',activateFree:'Activar gratis',deactivate:'Desactivar'},
 pt:{adminProtected:'Acesso Admin protegido',adminOnly:'Esta página é reservada à conta administradora WakhReek.',adminSubtitle:'Gestão protegida de lojas, pagamentos e WakhReek TV',notSubmitted:'Ainda não enviado',toReview:'Para verificar',approvedPayments:'Pagamentos aprovados',rejectedPayments:'Pagamentos recusados',pendingTvAds:'Anúncios TV pendentes',paymentsToReview:'💳 Pagamentos para verificar',paymentsWaiting:'⏳ Pagamentos ainda não enviados',approvedHistory:'✅ Pagamentos aprovados',rejectedHistory:'❌ Pagamentos recusados',noItem:'Nenhum item.',noPayment:'Sem pagamento',notConfigured:'Não configurado',notSubmittedYet:'Ainda não enviada',sellerReferenceWaiting:'⏳ Aguardando referência do vendedor',paymentMethodNotConfigured:'Método de pagamento não configurado',approvePayment:'Aprovar pagamento',rejectPayment:'Recusar pagamento',tvDivision:'📺 Divisão Publicidade — WakhReek TV',noTvAd:'Sem anúncios TV.',approveActivate:'Aprovar / Ativar',pause:'Pausa',finish:'Terminar',plan:'Plano',state:'Estado',adminActions:'Ações Admin',freeActivationNote:'A ativação gratuita Admin é independente do fluxo de pagamento.',activateFree:'Ativar grátis',deactivate:'Desativar'},
 de:{adminProtected:'Geschützter Admin-Zugang',adminOnly:'Diese Seite ist dem WakhReek-Administratorkonto vorbehalten.',adminSubtitle:'Geschützte Verwaltung von Shops, Zahlungen und WakhReek TV',notSubmitted:'Noch nicht eingereicht',toReview:'Zu prüfen',approvedPayments:'Genehmigte Zahlungen',rejectedPayments:'Abgelehnte Zahlungen',pendingTvAds:'Ausstehende TV-Anzeigen',paymentsToReview:'💳 Zahlungen zu prüfen',paymentsWaiting:'⏳ Noch nicht eingereichte Zahlungen',approvedHistory:'✅ Genehmigte Zahlungen',rejectedHistory:'❌ Abgelehnte Zahlungen',noItem:'Keine Elemente.',noPayment:'Keine Zahlung',notConfigured:'Nicht konfiguriert',notSubmittedYet:'Noch nicht eingereicht',sellerReferenceWaiting:'⏳ Verkäuferreferenz ausstehend',paymentMethodNotConfigured:'Zahlungsmethode nicht konfiguriert',approvePayment:'Zahlung genehmigen',rejectPayment:'Zahlung ablehnen',tvDivision:'📺 Werbeabteilung — WakhReek TV',noTvAd:'Keine TV-Anzeigen.',approveActivate:'Genehmigen / Aktivieren',pause:'Pause',finish:'Beenden',plan:'Plan',state:'Status',adminActions:'Admin-Aktionen',freeActivationNote:'Kostenlose Admin-Aktivierung bleibt vom Zahlungsablauf getrennt.',activateFree:'Kostenlos aktivieren',deactivate:'Deaktivieren'},
 nl:{adminProtected:'Beveiligde Admin-toegang',adminOnly:'Deze pagina is alleen voor het WakhReek-beheerdersaccount.',adminSubtitle:'Beveiligd beheer van winkels, betalingen en WakhReek TV',notSubmitted:'Nog niet ingediend',toReview:'Te beoordelen',approvedPayments:'Goedgekeurde betalingen',rejectedPayments:'Geweigerde betalingen',pendingTvAds:'TV-advertenties in afwachting',paymentsToReview:'💳 Betalingen te beoordelen',paymentsWaiting:'⏳ Betalingen nog niet ingediend',approvedHistory:'✅ Goedgekeurde betalingen',rejectedHistory:'❌ Geweigerde betalingen',noItem:'Geen items.',noPayment:'Geen betaling',notConfigured:'Niet geconfigureerd',notSubmittedYet:'Nog niet ingediend',sellerReferenceWaiting:'⏳ Wachten op verkopersreferentie',paymentMethodNotConfigured:'Betaalmethode niet geconfigureerd',approvePayment:'Betaling goedkeuren',rejectPayment:'Betaling weigeren',tvDivision:'📺 Advertentieafdeling — WakhReek TV',noTvAd:'Geen TV-advertenties.',approveActivate:'Goedkeuren / Activeren',pause:'Pauze',finish:'Beëindigen',plan:'Plan',state:'Status',adminActions:'Admin-acties',freeActivationNote:'Gratis Admin-activatie blijft los van de betaalstroom.',activateFree:'Gratis activeren',deactivate:'Deactiveren'}
}
const base={
 fr:{language:'Langue',loading:'Chargement...',refresh:'Actualiser',back:'Retour',signOut:'Déconnexion',mainNavigation:'Navigation principale',approve:'Approuver',reject:'Refuser',pending:'En attente',approved:'Approuvé',rejected:'Refusé',active:'Active',inactive:'Inactive',shop:'Boutique',shops:'Boutiques',payment:'Paiement',payments:'Paiements',amount:'Montant',country:'Pays',method:'Moyen',reference:'Référence',submittedAt:'Soumis le',admin:'Admin',communication:'Communication',market:'Marché'},
 ar:{language:'اللغة',loading:'جارٍ التحميل...',refresh:'تحديث',back:'رجوع',signOut:'تسجيل الخروج',mainNavigation:'التنقل الرئيسي',approve:'موافقة',reject:'رفض',pending:'قيد الانتظار',approved:'مقبول',rejected:'مرفوض',active:'نشطة',inactive:'غير نشطة',shop:'متجر',shops:'المتاجر',payment:'الدفع',payments:'المدفوعات',amount:'المبلغ',country:'البلد',method:'الوسيلة',reference:'المرجع',submittedAt:'تاريخ الإرسال',admin:'الإدارة',communication:'التواصل',market:'السوق'},
 en:{language:'Language',loading:'Loading...',refresh:'Refresh',back:'Back',signOut:'Sign out',mainNavigation:'Main navigation',approve:'Approve',reject:'Reject',pending:'Pending',approved:'Approved',rejected:'Rejected',active:'Active',inactive:'Inactive',shop:'Shop',shops:'Shops',payment:'Payment',payments:'Payments',amount:'Amount',country:'Country',method:'Method',reference:'Reference',submittedAt:'Submitted at',admin:'Admin',communication:'Communication',market:'Market'},
 es:{language:'Idioma',loading:'Cargando...',refresh:'Actualizar',back:'Volver',signOut:'Cerrar sesión',mainNavigation:'Navegación principal',approve:'Aprobar',reject:'Rechazar',pending:'Pendiente',approved:'Aprobado',rejected:'Rechazado',active:'Activa',inactive:'Inactiva',shop:'Tienda',shops:'Tiendas',payment:'Pago',payments:'Pagos',amount:'Importe',country:'País',method:'Método',reference:'Referencia',submittedAt:'Enviado el',admin:'Admin',communication:'Comunicación',market:'Mercado'},
 pt:{language:'Idioma',loading:'Carregando...',refresh:'Atualizar',back:'Voltar',signOut:'Sair',mainNavigation:'Navegação principal',approve:'Aprovar',reject:'Recusar',pending:'Pendente',approved:'Aprovado',rejected:'Recusado',active:'Ativa',inactive:'Inativa',shop:'Loja',shops:'Lojas',payment:'Pagamento',payments:'Pagamentos',amount:'Valor',country:'País',method:'Método',reference:'Referência',submittedAt:'Enviado em',admin:'Admin',communication:'Comunicação',market:'Mercado'},
 de:{language:'Sprache',loading:'Laden...',refresh:'Aktualisieren',back:'Zurück',signOut:'Abmelden',mainNavigation:'Hauptnavigation',approve:'Genehmigen',reject:'Ablehnen',pending:'Ausstehend',approved:'Genehmigt',rejected:'Abgelehnt',active:'Aktiv',inactive:'Inaktiv',shop:'Shop',shops:'Shops',payment:'Zahlung',payments:'Zahlungen',amount:'Betrag',country:'Land',method:'Methode',reference:'Referenz',submittedAt:'Eingereicht am',admin:'Admin',communication:'Kommunikation',market:'Markt'},
 nl:{language:'Taal',loading:'Laden...',refresh:'Vernieuwen',back:'Terug',signOut:'Uitloggen',mainNavigation:'Hoofdnavigatie',approve:'Goedkeuren',reject:'Weigeren',pending:'In afwachting',approved:'Goedgekeurd',rejected:'Geweigerd',active:'Actief',inactive:'Inactief',shop:'Winkel',shops:'Winkels',payment:'Betaling',payments:'Betalingen',amount:'Bedrag',country:'Land',method:'Methode',reference:'Referentie',submittedAt:'Ingediend op',admin:'Admin',communication:'Communicatie',market:'Markt'}
}
export const messages=Object.fromEntries(LANGUAGES.map(({code})=>[code,{...common,...admin[code],...base[code],...(extraMessages[code]||{})}]))
export function normalizeLanguage(lang){return LANGUAGE_CODES.has(lang)?lang:DEFAULT_LANGUAGE}
export function translate(lang,key,fallback){const l=normalizeLanguage(lang);return messages[l]?.[key]??messages[DEFAULT_LANGUAGE]?.[key]??fallback??key}
