const tvMessages={
 fr:{tvDiscover:'Découvrir • Regarder • Visiter',tvHeroText:'La vitrine vidéo de WakhReek relie la publicité aux boutiques du Market.',tvOpenMarket:'🛍️ Ouvrir Market',tvAdBand:'PUBLICITÉ WAKHREEK TV',tvAdBandItems:'• Boutiques • Produits • Marques',tvLoading:'Chargement TV…',tvSponsored:'PUBLICITÉ',tvViewShop:'Voir la boutique →',tvReady:'WakhReek TV est prêt',tvReadyText:'Les publicités approuvées apparaîtront ici. Aucun faux contenu publicitaire n’est affiché.',tvShops:'Boutiques WakhReek',tvDiscoverMarket:'Découvrir directement dans Market',tvSeeAll:'Tout voir',tvShopFallback:'Boutique WakhReek'},
 ar:{tvDiscover:'اكتشف • شاهد • زُر',tvHeroText:'واجهة الفيديو في WakhReek تربط الإعلانات بمتاجر السوق.',tvOpenMarket:'🛍️ فتح السوق',tvAdBand:'إعلانات WAKHREEK TV',tvAdBandItems:'• المتاجر • المنتجات • العلامات التجارية',tvLoading:'جارٍ تحميل TV…',tvSponsored:'إعلان',tvViewShop:'عرض المتجر ←',tvReady:'WakhReek TV جاهز',tvReadyText:'ستظهر هنا الإعلانات التي تمت الموافقة عليها. لا يتم عرض أي محتوى إعلاني مزيف.',tvShops:'متاجر WakhReek',tvDiscoverMarket:'اكتشف مباشرة داخل السوق',tvSeeAll:'عرض الكل',tvShopFallback:'متجر WakhReek'},
 en:{tvDiscover:'Discover • Watch • Visit',tvHeroText:'WakhReek’s video showcase connects advertising with Market shops.',tvOpenMarket:'🛍️ Open Market',tvAdBand:'WAKHREEK TV ADVERTISING',tvAdBandItems:'• Shops • Products • Brands',tvLoading:'Loading TV…',tvSponsored:'ADVERTISEMENT',tvViewShop:'View shop →',tvReady:'WakhReek TV is ready',tvReadyText:'Approved advertisements will appear here. No fake advertising content is displayed.',tvShops:'WakhReek Shops',tvDiscoverMarket:'Discover directly in Market',tvSeeAll:'See all',tvShopFallback:'WakhReek Shop'},
 es:{tvDiscover:'Descubrir • Ver • Visitar',tvHeroText:'El escaparate de vídeo de WakhReek conecta la publicidad con las tiendas del Mercado.',tvOpenMarket:'🛍️ Abrir Mercado',tvAdBand:'PUBLICIDAD WAKHREEK TV',tvAdBandItems:'• Tiendas • Productos • Marcas',tvLoading:'Cargando TV…',tvSponsored:'PUBLICIDAD',tvViewShop:'Ver la tienda →',tvReady:'WakhReek TV está listo',tvReadyText:'Los anuncios aprobados aparecerán aquí. No se muestra contenido publicitario falso.',tvShops:'Tiendas WakhReek',tvDiscoverMarket:'Descubrir directamente en el Mercado',tvSeeAll:'Ver todo',tvShopFallback:'Tienda WakhReek'},
 pt:{tvDiscover:'Descobrir • Ver • Visitar',tvHeroText:'A vitrine de vídeo da WakhReek liga a publicidade às lojas do Mercado.',tvOpenMarket:'🛍️ Abrir Mercado',tvAdBand:'PUBLICIDADE WAKHREEK TV',tvAdBandItems:'• Lojas • Produtos • Marcas',tvLoading:'Carregando TV…',tvSponsored:'PUBLICIDADE',tvViewShop:'Ver a loja →',tvReady:'WakhReek TV está pronta',tvReadyText:'Os anúncios aprovados aparecerão aqui. Nenhum conteúdo publicitário falso é exibido.',tvShops:'Lojas WakhReek',tvDiscoverMarket:'Descobrir diretamente no Mercado',tvSeeAll:'Ver tudo',tvShopFallback:'Loja WakhReek'},
 de:{tvDiscover:'Entdecken • Ansehen • Besuchen',tvHeroText:'Die Video-Schaufenster von WakhReek verbindet Werbung mit den Shops im Markt.',tvOpenMarket:'🛍️ Markt öffnen',tvAdBand:'WAKHREEK TV WERBUNG',tvAdBandItems:'• Shops • Produkte • Marken',tvLoading:'TV wird geladen…',tvSponsored:'WERBUNG',tvViewShop:'Shop ansehen →',tvReady:'WakhReek TV ist bereit',tvReadyText:'Genehmigte Anzeigen erscheinen hier. Es werden keine gefälschten Werbeinhalte angezeigt.',tvShops:'WakhReek Shops',tvDiscoverMarket:'Direkt im Markt entdecken',tvSeeAll:'Alle ansehen',tvShopFallback:'WakhReek Shop'},
 nl:{tvDiscover:'Ontdekken • Kijken • Bezoeken',tvHeroText:'De videovitrine van WakhReek verbindt advertenties met winkels in de Markt.',tvOpenMarket:'🛍️ Markt openen',tvAdBand:'WAKHREEK TV ADVERTENTIES',tvAdBandItems:'• Winkels • Producten • Merken',tvLoading:'TV laden…',tvSponsored:'ADVERTENTIE',tvViewShop:'Winkel bekijken →',tvReady:'WakhReek TV is klaar',tvReadyText:'Goedgekeurde advertenties verschijnen hier. Er wordt geen nep-advertentiecontent getoond.',tvShops:'WakhReek Winkels',tvDiscoverMarket:'Direct ontdekken in de Markt',tvSeeAll:'Alles bekijken',tvShopFallback:'WakhReek Winkel'}
}
export function tvTranslate(language,key,fallback){return tvMessages[language]?.[key]??tvMessages.fr?.[key]??fallback??key}
