'use client'
import Link from 'next/link'
import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabase} from '../../lib/supabase'
import styles from './communication.module.css'

const VAPID_PUBLIC_KEY = "BAaIzBNTHgNIiJF6-kX4Lf9nvhOsQqiiohQdJJyFKb1jkT4dVbOLmTyqtA5h1B_QwqVeHaiNYjgohVq_UIe2L2M";

export default function CommunicationPage(){
 const router=useRouter()
 const [me,setMe]=useState(null),[people,setPeople]=useState([]),[friendIds,setFriendIds]=useState(new Set()),[incomingRequests,setIncomingRequests]=useState([]),[outgoingRequests,setOutgoingRequests]=useState([]),[conversationMeta,setConversationMeta]=useState({}),[activePerson,setActivePerson]=useState(null),[conversationId,setConversationId]=useState(null),[messages,setMessages]=useState([]),[receipts,setReceipts]=useState({}),[text,setText]=useState(''),[filter,setFilter]=useState('toutes'),[status,setStatus]=useState(''),[recording,setRecording]=useState(false),[uploadingAudio,setUploadingAudio]=useState(false),[uploadingImage,setUploadingImage]=useState(false),[friendBox,setFriendBox]=useState(false),[phoneSearch,setPhoneSearch]=useState(''),[phoneResults,setPhoneResults]=useState([]),[phoneBusy,setPhoneBusy]=useState(false),[incomingCall,setIncomingCall]=useState(null),[currentCall,setCurrentCall]=useState(null),[callState,setCallState]=useState(''),[localStream,setLocalStream]=useState(null),[remoteStream,setRemoteStream]=useState(null)
 const messagesEndRef=useRef(null),messagesRef=useRef([]),mediaRecorderRef=useRef(null),mediaStreamRef=useRef(null),audioChunksRef=useRef([]),stopRecordingRequestedRef=useRef(false),audioMimeRef=useRef('audio/webm'),imageInputRef=useRef(null),peerRef=useRef(null),signalIdsRef=useRef(new Set()),pendingIceRef=useRef([]),answeringRef=useRef(false),localVideoRef=useRef(null),remoteVideoRef=useRef(null),remoteAudioRef=useRef(null),callLocalStreamRef=useRef(null),callRemoteStreamRef=useRef(null),ringtoneContextRef=useRef(null),ringtoneTimerRef=useRef(null),ringtoneNodesRef=useRef([])

 const withSignedMedia=useCallback(async m=>{if(!['audio','image'].includes(m?.message_type)||!m?.storage_path)return m;const{data,error}=await supabase.storage.from('communication-media').createSignedUrl(m.storage_path,3600);if(error)return m;return data?.signedUrl?{...m,media_url:data.signedUrl}:m},[])
 const refreshSidebar=useCallback(async user=>{if(!user)return;const[{data:foundPeople,error:pe},{data:fr,error:fe},{data:req,error:re},{data:members,error:me2}]=await Promise.all([supabase.rpc('find_people',{search_text:''}),supabase.from('friends').select('friend_id'),supabase.from('friend_requests').select('id,sender_id,receiver_id,status,created_at').eq('status','pending').order('created_at',{ascending:false}),supabase.from('conversation_members').select('conversation_id,user_id')]);if(pe||fe||re||me2){setStatus((pe||fe||re||me2).message);return}setPeople(foundPeople||[]);setFriendIds(new Set((fr||[]).map(x=>x.friend_id)));setIncomingRequests((req||[]).filter(x=>x.receiver_id===user.id));setOutgoingRequests((req||[]).filter(x=>x.sender_id===user.id));const map=new Map();(members||[]).forEach(x=>{if(x.user_id!==user.id)map.set(x.conversation_id,x.user_id)});const ids=[...map.keys()];if(!ids.length){setConversationMeta({});return}const{data:latest}=await supabase.from('messages').select('conversation_id,body,message_type,created_at').in('conversation_id',ids).order('created_at',{ascending:false});const lm=new Map();(latest||[]).forEach(x=>{if(!lm.has(x.conversation_id))lm.set(x.conversation_id,x)});const meta={};map.forEach((uid,id)=>meta[uid]={id,latest:lm.get(id)||null});setConversationMeta(meta)},[])

 async function registerPWAAndPush(user){
  try{
    if(typeof window==='undefined')return;
    if(!('serviceWorker' in navigator) || !('PushManager' in window))return;
    const reg = await navigator.serviceWorker.register('/sw.js');
    const perm = await Notification.requestPermission();
    if(perm!=='granted')return;
    const urlBase64ToUint8Array = (base64String) => {
      const padding = '='.repeat((4 - base64String.length % 4) % 4);
      const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
      const rawData = window.atob(base64);
      const outputArray = new Uint8Array(rawData.length);
      for(let i=0;i<rawData.length;++i)outputArray[i]=rawData.charCodeAt(i);
      return outputArray;
    };
    let sub = await reg.pushManager.getSubscription();
    if(!sub){
      sub = await reg.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY)
      });
    }
    await supabase.from('push_subscriptions').upsert({
      user_id: user.id,
      subscription: sub.toJSON()
    }, { onConflict: 'user_id' });
    console.log('Push registered');
  }catch(e){ console.log('Push error', e); }
 }

 useEffect(()=>{supabase.auth.getUser().then(({data,error})=>{if(error||!data?.user){router.replace('/');return}setMe(data.user);refreshSidebar(data.user);registerPWAAndPush(data.user)})},[router,refreshSidebar])
 const loadMessages=useCallback(async id=>{const{data,error}=await supabase.from('messages').select('*').eq('conversation_id',id).order('created_at',{ascending:true});if(error){setStatus(error.message);return}const old=new Map(messagesRef.current.map(m=>[m.id,m]));const next=await Promise.all((data||[]).map(m=>old.get(m.id)?.media_url?{...m,media_url:old.get(m.id).media_url}:withSignedMedia(m)));messagesRef.current=next;setMessages(next)},[withSignedMedia])
 useEffect(()=>{if(!conversationId)return;loadMessages(conversationId);const ch=supabase.channel(`messages:${conversationId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${conversationId}`},async p=>{const m=await withSignedMedia(p.new);setMessages(c=>{if(c.some(x=>x.id===m.id))return c;const next=[...c,m];messagesRef.current=next;return next});if(me)refreshSidebar(me)}).subscribe();const timer=setInterval(()=>loadMessages(conversationId),3000);const onVisible=()=>{if(document.visibilityState==='visible')loadMessages(conversationId)};document.addEventListener('visibilitychange',onVisible);window.addEventListener('focus',onVisible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',onVisible);window.removeEventListener('focus',onVisible);supabase.removeChannel(ch)}},[conversationId,loadMessages,me,refreshSidebar,withSignedMedia])
 useEffect(()=>{if(!me||!conversationId||!messages.length){setReceipts({});return}let cancelled=false;async function syncReceipts(){const incoming=messages.filter(m=>m.sender_id!==me.id);if(incoming.length){await Promise.all(incoming.map(m=>supabase.rpc('mark_message_delivered',{p_message_id:m.id})));if(document.visibilityState==='visible')await supabase.rpc('mark_conversation_read',{p_conversation_id:conversationId})}const ids=messages.map(m=>m.id);const{data,error}=await supabase.from('message_receipts').select('message_id,user_id,delivered_at,read_at').in('message_id',ids);if(cancelled)return;if(error){setStatus(error.message);return}const map={};(data||[]).forEach(r=>{if(r.user_id!==me.id)map[r.message_id]=r});setReceipts(map)}syncReceipts();const timer=setInterval(syncReceipts,3000);const onVisible=()=>{if(document.visibilityState==='visible')syncReceipts()};document.addEventListener('visibilitychange',onVisible);window.addEventListener('focus',onVisible);return()=>{cancelled=true;clearInterval(timer);document.removeEventListener('visibilitychange',onVisible);window.removeEventListener('focus',onVisible)}},[me,conversationId,messages])
 useEffect(()=>{if(!me)return;const timer=setInterval(()=>refreshSidebar(me),5000);return()=>clearInterval(timer)},[me,refreshSidebar])
 useEffect(()=>{messagesRef.current=messages},[messages]);useEffect(()=>messagesEndRef.current?.scrollIntoView({behavior:'smooth'}),[messages]);useEffect(()=>()=>mediaStreamRef.current?.getTracks().forEach(t=>t.stop()),[])

 function ensureRingtoneContext(){if(typeof window==='undefined')return null;const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return null;if(!ringtoneContextRef.current)ringtoneContextRef.current=new AudioCtx();return ringtoneContextRef.current}
 async function unlockRingtone(){const ctx=ensureRingtoneContext();if(ctx?.state==='suspended'){try{await ctx.resume()}catch{}}}
 function stopRingtone(){if(ringtoneTimerRef.current){clearInterval(ringtoneTimerRef.current);ringtoneTimerRef.current=null}ringtoneNodesRef.current.forEach(n=>{try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}});ringtoneNodesRef.current=[];if(navigator.vibrate)navigator.vibrate(0)}
 function playRingtonePattern(){const ctx=ensureRingtoneContext();if(!ctx||ctx.state!=='running')return;const now=ctx.currentTime;const notes=[{f:659.25,t:0,d:.28,v:.18},{f:783.99,t:.34,d:.28,v:.16},{f:987.77,t:.68,d:.38,v:.14},{f:783.99,t:1.18,d:.24,v:.11},{f:987.77,t:1.5,d:.42,v:.13}];notes.forEach(({f,t,d,v})=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(f,now+t);gain.gain.setValueAtTime(.0001,now+t);gain.gain.exponentialRampToValueAtTime(v,now+t+.025);gain.gain.exponentialRampToValueAtTime(.0001,now+t+d);osc.connect(gain);gain.connect(ctx.destination);osc.start(now+t);osc.stop(now+t+d+.03);ringtoneNodesRef.current.push(osc,gain)});if(navigator.vibrate)navigator.vibrate([180,90,180,420])}
 async function startRingtone(){stopRingtone();await unlockRingtone();playRingtonePattern();ringtoneTimerRef.current=setInterval(playRingtonePattern,2400)}
 useEffect(()=>{const unlock=()=>unlockRingtone();window.addEventListener('pointerdown',unlock,{passive:true});window.addEventListener('keydown',unlock);return()=>{window.removeEventListener('pointerdown',unlock);window.removeEventListener('keydown',unlock)}},[])
 useEffect(()=>{if(incomingCall&&!currentCall)startRingtone();else stopRingtone();return()=>stopRingtone()},[incomingCall?.id,currentCall?.id])

 function stopCallMedia(){stopRingtone();peerRef.current?.close();peerRef.current=null;signalIdsRef.current=new Set();pendingIceRef.current=[];callLocalStreamRef.current?.getTracks().forEach(t=>t.stop());callRemoteStreamRef.current?.getTracks().forEach(t=>t.stop());callLocalStreamRef.current=null;callRemoteStreamRef.current=null;setLocalStream(null);setRemoteStream(null);setCurrentCall(null);setIncomingCall(null);setCallState('')}
 async function sendSignal(callId,type,payload){if(!me)throw new Error('Utilisateur non connecté.');const{error}=await supabase.from('call_signals').insert({call_id:callId,sender_id:me.id,signal_type:type,payload});if(error)throw error}
 async function flushPendingIce(pc){if(!pc?.remoteDescription)return;const queued=[...pendingIceRef.current];pendingIceRef.current=[];for(const row of queued){try{await pc.addIceCandidate(new RTCIceCandidate(row.payload))}catch(e){setStatus(e.message)}}}
 async function makePeer(callId,stream){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});peerRef.current=pc;stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const s=e.streams?.[0]||new MediaStream([e.track]);callRemoteStreamRef.current=s;setRemoteStream(s)};pc.onicecandidate=e=>{if(e.candidate)sendSignal(callId,'ice',e.candidate.toJSON()).catch(err=>setStatus(err.message))};pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected')setCallState('Connecté');if(['failed','closed'].includes(pc.connectionState))setCallState('Connexion terminée')};return pc}
 async function applySignal(row){if(!row||row.sender_id===me?.id||signalIdsRef.current.has(row.id)||!peerRef.current)return;signalIdsRef.current.add(row.id);const pc=peerRef.current;try{if(row.signal_type==='answer'&&!pc.currentRemoteDescription){await pc.setRemoteDescription(new RTCSessionDescription(row.payload));await flushPendingIce(pc);setCallState('Connecté')}else if(row.signal_type==='offer'&&!pc.currentRemoteDescription){await pc.setRemoteDescription(new RTCSessionDescription(row.payload));await flushPendingIce(pc)}else if(row.signal_type==='ice'){if(!pc.remoteDescription){pendingIceRef.current.push(row);return}await pc.addIceCandidate(new RTCIceCandidate(row.payload))}}catch(e){setStatus(e.message)}}
 async function loadCallSignals(callId){const{data,error}=await supabase.from('call_signals').select('*').eq('call_id',callId).order('id',{ascending:true});if(error){setStatus(error.message);return}for(const row of data||[])await applySignal(row)}
 async function startCall(type){if(!me||!conversationId||!activePerson||currentCall||incomingCall)return;if(!navigator.mediaDevices?.getUserMedia){setStatus('Appel non supporté sur cet appareil.');return}try{setCallState('Préparation…');pendingIceRef.current=[];const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:type==='video'});callLocalStreamRef.current=stream;setLocalStream(stream);const{data:call,error}=await supabase.from('call_sessions').insert({conversation_id:conversationId,caller_id:me.id,call_type:type,status:'ringing'}).select('*').single();if(error){stream.getTracks().forEach(t=>t.stop());callLocalStreamRef.current=null;setLocalStream(null);setCallState('');setStatus(error.message);return}setCurrentCall({...call,direction:'outgoing'});setCallState(type==='video'?'Appel vidéo…':'Appel audio…');const pc=await makePeer(call.id,stream);const offer=await pc.createOffer();await pc.setLocalDescription(offer);const localOffer=pc.localDescription;if(localOffer?.type!=='offer'||!localOffer.sdp)throw new Error("L'offre WebRTC locale est invalide.");await sendSignal(call.id,'offer',{type:localOffer.type,sdp:localOffer.sdp});try{await supabase.functions.invoke('send-call-push',{body:{call_id:call.id}})}catch(e){console.log('push invoke error',e)}}catch(e){stopCallMedia();setStatus(e?.name==='NotAllowedError'?'Autorisez le microphone et la caméra.':e.message)}}
 async function answerCall(){const call=incomingCall;if(!call||!me||answeringRef.current)return;answeringRef.current=true;stopRingtone();try{setCallState('Connexion…');pendingIceRef.current=[];const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:call.call_type==='video'});callLocalStreamRef.current=stream;setLocalStream(stream);const pc=await makePeer(call.id,stream);const{data:signals,error}=await supabase.from('call_signals').select('*').eq('call_id',call.id).order('id',{ascending:true});if(error)throw error;const offer=(signals||[]).find(s=>s.signal_type==='offer'&&s.sender_id!==me.id);if(!offer)throw new Error("Signal d'appel introuvable.");signalIdsRef.current.add(offer.id);await pc.setRemoteDescription(new RTCSessionDescription(offer.payload));const answer=await pc.createAnswer();await pc.setLocalDescription(answer);const localAnswer=pc.localDescription;if(localAnswer?.type!=='answer'||!localAnswer.sdp)throw new Error('La réponse WebRTC locale est invalide.');const{error:acceptError}=await supabase.rpc('accept_call',{p_call_id:call.id,p_answer:{type:localAnswer.type,sdp:localAnswer.sdp}});if(acceptError)throw acceptError;setCurrentCall({...call,direction:'incoming',status:'accepted'});setIncomingCall(null);setCallState('Connecté');for(const row of signals||[]){if(row.id!==offer.id)await applySignal(row)}await flushPendingIce(pc)}catch(e){stopCallMedia();setStatus(e?.name==='NotAllowedError'?'Autorisez le microphone et la caméra.':e?.message||"Impossible d'accepter l'appel.")}finally{answeringRef.current=false}}
 async function rejectCall(){if(!incomingCall)return;stopRingtone();await supabase.from('call_sessions').update({status:'rejected',ended_at:new Date().toISOString()}).eq('id',incomingCall.id);setIncomingCall(null)}
 async function endCall(){const call=currentCall;if(call)await supabase.from('call_sessions').update({status:'ended',ended_at:new Date().toISOString()}).eq('id',call.id);stopCallMedia()}

 useEffect(()=>{if(!me)return;let cancelled=false;async function checkIncoming(){const{data}=await supabase.from('call_sessions').select('*').eq('status','ringing').neq('caller_id',me.id).order('created_at',{ascending:false}).limit(1);if(!cancelled&&data?.[0]&&!currentCall)setIncomingCall(data[0])}checkIncoming();const ch=supabase.channel(`incoming-calls:${me.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_sessions'},p=>{const c=p.new;if(c.caller_id!==me.id&&c.status==='ringing'&&!currentCall)setIncomingCall(c)}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'call_sessions'},p=>{const c=p.new;if(currentCall?.id===c.id&&['ended','rejected'].includes(c.status))stopCallMedia();if(incomingCall?.id===c.id&&c.status!=='ringing'){stopRingtone();setIncomingCall(null)}}).subscribe();return()=>{cancelled=true;supabase.removeChannel(ch)}},[me,currentCall,incomingCall])
 useEffect(()=>{if(!currentCall?.id)return;const ch=supabase.channel(`call-signals:${currentCall.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_signals',filter:`call_id=eq.${currentCall.id}`},p=>applySignal(p.new)).subscribe();loadCallSignals(currentCall.id);return()=>supabase.removeChannel(ch)},[currentCall?.id,me])
 useEffect(()=>{if(localVideoRef.current)localVideoRef.current.srcObject=localStream||null},[localStream,currentCall]);useEffect(()=>{if(remoteVideoRef.current)remoteVideoRef.current.srcObject=remoteStream||null;if(remoteAudioRef.current)remoteAudioRef.current.srcObject=remoteStream||null},[remoteStream,currentCall])
 useEffect(()=>()=>{stopRingtone();ringtoneContextRef.current?.close?.();peerRef.current?.close();callLocalStreamRef.current?.getTracks().forEach(t=>t.stop());callRemoteStreamRef.current?.getTracks().forEach(t=>t.stop())},[])

 const peopleById=useMemo(()=>new Map(people.map(p=>[p.id,p])),[people]),incomingBySender=useMemo(()=>new Map(incomingRequests.map(r=>[r.sender_id,r])),[incomingRequests]),outgoingByReceiver=useMemo(()=>new Map(outgoingRequests.map(r=>[r.receiver_id,r])),[outgoingRequests])
 const visiblePeople=useMemo(()=>{if(filter==='demandes'||filter==='groupes')return[];let list=people.filter(p=>friendIds.has(p.id)||conversationMeta[p.id]);if(filter==='amis')list=list.filter(p=>friendIds.has(p.id));return [...list].sort((a,b)=>(conversationMeta[b.id]?.latest?.created_at||'').localeCompare(conversationMeta[a.id]?.latest?.created_at||''))},[people,friendIds,conversationMeta,filter])
 async function searchPhone(e){e?.preventDefault();const q=phoneSearch.trim();if(!q)return;setPhoneBusy(true);setStatus('');const{data,error}=await supabase.rpc('find_people_by_phone',{search_text:q});setPhoneBusy(false);if(error){setStatus(error.message);return}setPhoneResults(data||[])}
 async function connectPerson(person){if(!me||!person?.id)return;setStatus('Connexion…');const{data,error}=await supabase.rpc('connect_registered_user',{other_user:person.id});if(error){setStatus(error.message);return}await refreshSidebar(me);setFriendBox(false);setPhoneResults([]);setPhoneSearch('');setActivePerson(person);setConversationId(data);setFilter('toutes');setStatus('Connecté ✅')}
 async function removeFriend(person){if(!me||!friendIds.has(person.id))return;if(!window.confirm(`Supprimer ${person.display_name||person.phone||'cet ami'} de vos amis ?`))return;const{error}=await supabase.rpc('remove_friend',{other_user:person.id});if(error){setStatus(error.message);return}setStatus('Ami supprimé.');await refreshSidebar(me)}
 async function openConversation(person){let id=conversationMeta[person.id]?.id;if(!id){const{data,error}=await supabase.rpc('connect_registered_user',{other_user:person.id});if(error){setStatus(error.message);return}id=data;await refreshSidebar(me)}setActivePerson(person);setConversationId(id)}
 async function sendMessage(e){e.preventDefault();const body=text.trim();if(!body||!conversationId||!me)return;setText('');const{error}=await supabase.from('messages').insert({conversation_id:conversationId,sender_id:me.id,body,message_type:'text'});if(error){setText(body);setStatus(error.message)}}
 async function sendImage(e){const file=e.target.files?.[0];e.target.value='';if(!file||!conversationId||!me)return;const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type)){setStatus('Format image non supporté. Utilisez JPG, PNG ou WebP.');return}if(file.size>50*1024*1024){setStatus('Image trop volumineuse (maximum 50 MB).');return}setUploadingImage(true);setStatus('Envoi de l’image…');const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const path=`${conversationId}/${me.id}/${Date.now()}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}.${ext}`;const{error:ue}=await supabase.storage.from('communication-media').upload(path,file,{contentType:file.type,upsert:false});if(ue){setUploadingImage(false);setStatus(ue.message);return}const{error}=await supabase.from('messages').insert({conversation_id:conversationId,sender_id:me.id,body:'Photo',message_type:'image',storage_path:path,media_url:null});setUploadingImage(false);setStatus(error?error.message:'');if(error)await supabase.storage.from('communication-media').remove([path]);else await loadMessages(conversationId)}
 async function finalizeVoiceRecording(stream){setRecording(false);stream.getTracks().forEach(t=>t.stop());const actual=audioMimeRef.current||'audio/webm',base=actual.split(';')[0],ext=base.includes('mp4')?'m4a':base.includes('ogg')?'ogg':base.includes('mpeg')?'mp3':'webm',blob=new Blob(audioChunksRef.current,{type:actual});audioChunksRef.current=[];mediaRecorderRef.current=null;mediaStreamRef.current=null;if(!blob.size){setStatus('Aucun son enregistré. Réessayez.');return}setUploadingAudio(true);setStatus('Envoi du message vocal…');const path=`${conversationId}/${me.id}/${Date.now()}.${ext}`;const{error:ue}=await supabase.storage.from('communication-media').upload(path,blob,{contentType:base,upsert:false});if(ue){setUploadingAudio(false);setStatus(ue.message);return}const{error}=await supabase.from('messages').insert({conversation_id:conversationId,sender_id:me.id,body:'Message vocal',message_type:'audio',storage_path:path,media_url:null});setUploadingAudio(false);if(error){setStatus(error.message);await supabase.storage.from('communication-media').remove([path]);return}setStatus('');await loadMessages(conversationId)}
 function createVoiceRecorder(stream,mimeType){const rec=mimeType?new MediaRecorder(stream,{mimeType}):new MediaRecorder(stream);mediaRecorderRef.current=rec;audioMimeRef.current=rec.mimeType||mimeType||'audio/webm';rec.ondataavailable=e=>{if(e.data?.size)audioChunksRef.current.push(e.data)};rec.onerror=e=>setStatus(e?.error?.message||'Erreur d’enregistrement audio.');rec.onstop=async()=>{if(!stopRecordingRequestedRef.current&&stream.active&&stream.getAudioTracks().some(t=>t.readyState==='live')){try{const next=createVoiceRecorder(stream,mimeType);next.start(250);return}catch(e){setStatus(e.message)}}await finalizeVoiceRecording(stream)};return rec}
 async function startVoiceRecording(){if(!activePerson||!conversationId||!me||recording||uploadingAudio||uploadingImage)return;if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setStatus("L'enregistrement audio n'est pas supporté.");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaStreamRef.current=stream;audioChunksRef.current=[];stopRecordingRequestedRef.current=false;const types=['audio/mp4','audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/webm','audio/ogg'];const mt=types.find(t=>MediaRecorder.isTypeSupported?.(t))||'';const rec=createVoiceRecorder(stream,mt);rec.start(250);setStatus('');setRecording(true)}catch(e){setRecording(false);setStatus(e?.name==='NotAllowedError'?'Autorisez le microphone.':e.message)}}
 function stopVoiceRecording(){const r=mediaRecorderRef.current;if(!r||r.state==='inactive')return;stopRecordingRequestedRef.current=true;try{if(r.state==='recording')r.requestData()}catch{}r.stop()}
 async function signOut(){await supabase.auth.signOut();router.replace('/')}
 function fmt(v){return v?new Date(v).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):''}
 function initials(p){return(p?.display_name||p?.email||'WR').slice(0,2).toUpperCase()}
 function latest(p){const m=conversationMeta[p.id]?.latest;if(!m)return friendIds.has(p.id)?'Contact WakhReek':'Discussion';if(m.message_type==='audio')return'🎙 Message vocal';if(m.message_type==='image')return'📷 Photo';return m.body||'Message'}
 function receiptMark(m){if(m.sender_id!==me?.id)return null;const r=receipts[m.id];if(r?.read_at)return <span className={styles.readReceipt}>✓✓</span>;if(r?.delivered_at)return <span>✓✓</span>;return <span>✓</span>}
 const incomingCaller=peopleById.get(incomingCall?.caller_id)

 return <div className={styles.page}>
  <header className={styles.topbar}><div className={styles.brand}><img src="/wakhreek-logo.svg" alt="WakhReek" className={styles.logo}/><div><strong>WakhReek</strong><span>- Onley Took</span></div></div><div className={styles.topActions}><button className={styles.iconButton} onClick={()=>me&&refreshSidebar(me)}>↻</button><div className={styles.meBlock}><div className={styles.avatarSmall}>{initials({email:me?.email})}</div><div><strong>{me?.email||'WakhReek'}</strong><span>En ligne</span></div></div><button className={styles.logout} onClick={signOut}>↪ Déconnexion</button></div></header>
  <nav className={styles.mainNav}><Link className={styles.navActive} href="/communication">💬 Communication</Link><Link href="/market">🛍 Market</Link><Link href="/tv">📺 WakhReek TV</Link></nav>
  <div className={`${styles.shell} ${activePerson?styles.hasActive:''}`}><aside className={styles.sidebar}>
   <div className={styles.searchWrap}><button type="button" className={styles.addFriendOpen} onClick={()=>{setFriendBox(v=>!v);setPhoneResults([]);setPhoneSearch('')}}>＋</button><span>⌕</span><input readOnly placeholder="Rechercher ou démarrer une discussion"/></div>
   {friendBox&&<div className={styles.friendBox}><div className={styles.friendBoxHead}><strong>Contacter un utilisateur</strong><button onClick={()=>setFriendBox(false)}>×</button></div><form onSubmit={searchPhone}><input type="tel" value={phoneSearch} onChange={e=>setPhoneSearch(e.target.value)} placeholder="Numéro de téléphone" autoFocus/><button type="submit" disabled={phoneBusy}>{phoneBusy?'…':'⌕'}</button></form>{phoneResults.map(p=>{const isFriend=friendIds.has(p.id);return <div className={styles.phoneResult} key={p.id}><div className={styles.contactAvatar}>{initials(p)}</div><div><strong>{p.display_name||p.phone||'Utilisateur WakhReek'}</strong><span>{p.phone}</span></div>{isFriend?<button className={styles.friendAction} onClick={()=>openConversation(p)}>Message</button>:<button className={styles.friendAction} onClick={()=>connectPerson(p)}>Contacter</button>}</div>})}{phoneSearch&&phoneResults.length===0&&!phoneBusy&&<p className={styles.friendHint}>Tapez le numéro puis appuyez sur recherche.</p>}</div>}
   <div className={styles.filters}>{[['toutes','Toutes'],['amis','Contacts'],['groupes','Groupes']].map(([k,l])=><button key={k} className={filter===k?styles.filterActive:''} onClick={()=>setFilter(k)}>{l}</button>)}</div>
   <div className={styles.contactList}>{visiblePeople.map(p=><div className={styles.contactRow} key={p.id}><button className={styles.personMain} onClick={()=>openConversation(p)}><div className={styles.contactAvatar}>{initials(p)}<i/></div><div className={styles.contactCopy}><div><strong>{p.display_name||p.email}</strong><time>{fmt(conversationMeta[p.id]?.latest?.created_at)}</time></div><p>{latest(p)}</p></div></button></div>)}{!visiblePeople.length&&<p className={styles.empty}>Aucune conversation</p>}</div><div className={styles.encryption}>🔒 Vos messages personnels sont <strong>protégés</strong></div>
  </aside><main className={styles.chat}><header className={styles.chatHeader}><button className={styles.mobileBack} onClick={()=>{setActivePerson(null);setConversationId(null);setMessages([]);setReceipts({});messagesRef.current=[]}}>←</button><div className={styles.chatIdentity}><div className={styles.avatarMedium}>{initials(activePerson)}</div><div><strong>{activePerson?.display_name||'WakhReek Communication'}</strong><span>{activePerson?'En ligne':'Choisissez un contact'}</span></div></div><div className={styles.chatActions}><button>⌕</button><button type="button" onClick={()=>startCall('audio')} disabled={!activePerson||!!currentCall||!!incomingCall}>☎</button><button type="button" onClick={()=>startCall('video')} disabled={!activePerson||!!currentCall||!!incomingCall}>▣</button><button>⋮</button></div></header><section className={styles.messages}>{!activePerson&&<div className={styles.welcome}>Choisissez une discussion pour commencer.</div>}{messages.map(m=>{const mine=m.sender_id===me?.id;return <div className={`${styles.messageRow} ${mine?styles.mine:''}`} key={m.id}><div className={`${styles.bubble} ${mine?styles.bubbleMine:''}`}>{m.message_type==='audio'&&m.media_url?<audio controls preload="metadata" src={m.media_url} className={styles.audio}/>:m.message_type==='image'&&m.media_url?<img src={m.media_url} alt="Photo" className={styles.messageImage}/>:<p>{m.body}</p>}<time>{fmt(m.created_at)} {receiptMark(m)}</time></div></div>})}{status&&<div className={styles.status}>{status}</div>}<div ref={messagesEndRef}/></section><form className={styles.composer} onSubmit={sendMessage}><button disabled>☺</button><button disabled>⌕</button><input value={text} onChange={e=>setText(e.target.value)} placeholder={uploadingImage?'Envoi de l’image…':recording?'Enregistrement…':uploadingAudio?'Envoi du vocal…':activePerson?'Message':'Choisissez une conversation'} disabled={!activePerson||recording||uploadingAudio||uploadingImage}/><button disabled>📎</button><input ref={imageInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={sendImage} style={{display:'none'}}/><button type="button" onClick={()=>imageInputRef.current?.click()} disabled={!activePerson||recording||uploadingAudio||uploadingImage}>📷</button>{text.trim()?<button type="submit" className={styles.send}>➤</button>:<button type="button" className={`${styles.send} ${recording?styles.recording:''}`} onClick={recording?stopVoiceRecording:startVoiceRecording} disabled={!activePerson||uploadingAudio||uploadingImage}>{recording?'■':'🎙'}</button>}</form></main></div>

  {incomingCall&&!currentCall&&<div className={styles.callOverlay}><div className={styles.callPanel}><div className={styles.callAvatar}>{initials(incomingCaller)}</div><h3>{incomingCaller?.display_name||'Appel WakhReek'}</h3><p>{incomingCall.call_type==='video'?'Appel vidéo entrant':'Appel audio entrant'}</p><div className={styles.callButtons}><button className={styles.rejectCall} onClick={rejectCall}>✕</button><button className={styles.acceptCall} onClick={answerCall}>✓</button></div></div></div>}
  {currentCall&&<div className={styles.callOverlay}><div className={`${styles.callPanel} ${currentCall.call_type==='video'?styles.videoPanel:''}`}><h3>{activePerson?.display_name||incomingCaller?.display_name||'WakhReek'}</h3><p>{callState||'Connexion…'}</p>{currentCall.call_type==='video'?<div className={styles.videoStage}><video ref={remoteVideoRef} autoPlay playsInline className={styles.remoteVideo}/><video ref={localVideoRef} autoPlay muted playsInline className={styles.localVideo}/></div>:<><div className={styles.callAvatar}>{initials(activePerson||incomingCaller)}</div><audio ref={remoteAudioRef} autoPlay/></>}<div className={styles.callButtons}><button className={styles.rejectCall} onClick={endCall}>✕</button></div></div></div>}
 </div>
}

